### ISSUE TITLE
Incorrect `opsz` range in Designspace file generated from Glyphs project

### ISSUE THREAD

**Issue by clauseggers** [googlefonts/fontmake#1002]
When I try to generate a VF from a Glyphs project, I get the following error on the Italic Glyphs file:
```
<axes>
  <axis tag="opsz" name="Optical size" minimum="5" maximum="120" default="120">
    <map input="5" output="5"/>
    <map input="8" output="40"/>
    <map input="12" output="60"/>
    <map input="24" output="75"/>
    <map input="42" output="90"/>
    <map input="62" output="100"/>
    <map input="88" output="110"/>
    <map input="120" output="120"/>
  </axis>
  <axis tag="wdth" name="Width" minimum="50" maximum="150" default="50"/>
  <axis tag="wght" name="Weight" minimum="400" maximum="900" default="400"/>
  <axis tag="ital" name="Italic" minimum="1" maximum="1" default="1"/>
</axes>
```

The `opsz` is given as 5–120 when it is in fact 5–1200 in the Glyphs file. I can’t find this 120 value anywhere in the Glyphs file. The Roman is set up just like the Italic, and that one does not show this error. The `axes` table in the Roman Designspace file is:
```
<axes>
  <axis tag="opsz" name="Optical size" minimum="5" maximum="1200" default="1200">
    <map input="5" output="5"/>
    <map input="6" output="200"/>
    <map input="7" output="325"/>
    <map input="8" output="400"/>
    <map input="12" output="550"/>
    <map input="16" output="640"/>
    <map input="21" output="700"/>
    <map input="32" output="800"/>
    <map input="72" output="980"/>
    <map input="96" output="1020"/>
    <map input="1200" output="1200"/>
  </axis>
  <axis tag="wdth" name="Width" minimum="50" maximum="150" default="50"/>
  <axis tag="wght" name="Weight" minimum="300" maximum="900" default="300">
    <map input="300" output="360"/>
    <map input="900" output="900"/>
  </axis>
</axes>
```

I can also see that the `wght` axis has a minimum value of 400 in the Italic and 300 in the Roman.

As far as I can see, the Roman and Italic Glyphs files are identically set up, except from the Italic having a hidden Italic axis set to 1.

If you want to see the files then they are here: https://github.com/clauseggers/Playfair/tree/master/sources

**Comment by clauseggers** [comment]
> Ah! it looks like you did disable the "Axis Mappings" parameter, but somehow fontmake (actually glyphsLib) is still reading that.. I think that's a bug. For now, can you please just delete the disabled "Axis Mappings" and see if that works?

I got further this time. A bit strange why the Roman – which has the same disabled parameter – didn’t bail out.

Anyway, now I got to `Generating fonts from Designspace failed: Tried to end an empty contour.` Which might be the same glyph as the Roman. Gonna try fixing it.

**Comment by anthrotype** [comment]
> Tried to end an empty contour.

I merged https://github.com/fonttools/fonttools/pull/3145, try installing fonttools from github it should work around that

**Comment by anthrotype** [comment]
no, that way you get the stable release from PyPI.
temporarily use this, until the next fonttools release is out:

```
$ pip install -e git+https://github.com/fonttools/fonttools.git#egg=FontTools
```

**Comment by clauseggers** [comment]
Sorry, but I am getting the same error, also with the fresh fonttools from github:
```
fontmake: Error: In 'Playfair-2_1-Italic.glyphs' -> 'master_ufo/Playfair.designspace': Generating fonts from Designspace failed: Tried to end an empty contour.
```

**Comment by anthrotype** [comment]
Try again, maybe pip uninstall fonttools and the install again, make sure you are installing it in the same environment where fontmake itself is

**Comment by clauseggers** [comment]
Both `fontmake` and `fonttools` are in each their own VirtualEnv, then linked to `~/.local/bin` which is in my path. I’m gonna try restarting the Mac.

**Comment by anthrotype** [comment]
> fontmake and fonttools are in each their own VirtualEnv

no that's not how it's supposed to work, you want to install fonttools (library) in the same virtual environment where fontmake (application) is installed, such that fontmake can import that.
It's good you wish to keep distinct applications each in their own virtual environments, but for this to work you want to _not_ keep them distinct.

**Comment by anthrotype** [comment]
basically, you need to activate the venv where fontmake is installed and use that venv's pip command to install the fonttools from github

**Comment by clauseggers** [comment]
Success. Thank you for your speedy fix.
