### ISSUE TITLE
How to turn off default filters?

### ISSUE THREAD

**Issue by yanone** [googlefonts/fontmake#1023]
I'm generating a variable TTF like so:
`fontmake -g $TEMPSOURCE -o variable --output-path $VF --verbose WARNING --check-compatibility --filter yanonefontproduction.ufo2ft.filters.tashkeelPositions::TashkeelPositionsFilter`

I'm not sure how to check explicitly, but it appears like the `DecomposeTransformedComponents` and `FlattenComponents` filters are called on the font. But I don't want them called and produce a lean web TTF.

How do I exclude them?

My understanding from [this discussion](https://github.com/googlefonts/fontmake/issues/872#issuecomment-1091970056) was that nothing needs to be done to turn off all filters and `...` needs to be set to call the UFO’s filters implicitly. In my case, the UFOs don't have any filters and I want the only filter to be my custom filter as noted in the `fontmake` call.

**Comment by yanone** [comment]
Btw, I also tried `--filter "None" --filter yanonefontproduction.ufo2ft.filters.tashkeelPositions::TashkeelPositionsFilter`, analog to _--feature-writer "None"_ as explained [here](https://github.com/googlefonts/fontmake/blob/main/USAGE.md#feature-writing).

**Comment by anthrotype** [comment]
> it appears like the DecomposeTransformedComponents and FlattenComponents filters are called on the font

those are not be enabled by default, they are opt-in.. why do you say they are enabled? do you see any logging messages pertaining to them?

**Comment by yanone** [comment]
> why do you say they are enabled?

By opening the generated font in Glyphs and checking individual glyphs. 

Actually, the nested components seem to be intact, but glyphs with transformed components are decomposed. I searched through fontmake's source code a little bit and couldn't find that this is hard-coded anywhere.

> do you see any logging messages pertaining to them?

No, it's waaaay too much output. I may have to filter for it somehow. I did perform a simple text search for the filter's name and couldn't find anything yet, but the text buffer is set to 100,000 lines only at the moment, so the top part of the output already disappears.

**Comment by anthrotype** [comment]
are you running fontmake through gftools builder? I think that enables those two by default

**Comment by yanone** [comment]
No, exactly not. I'm trying to recreate the build process outside of gftools because I want to control the process in detail and get rid of the filters that gftools sets. I posted the exact command I used in the top comment.

And btw, the other issue (https://github.com/googlefonts/gftools/issues/703) is directly linked of course. I simply assumed that those filters are set by default in fontmake by checking the font outlines.

**Comment by anthrotype** [comment]
> glyphs with transformed components are decomposed

ufo2ft's TTFInterpolatablePreProcessor will decompose those composite glyphs where a component has different transforms in different masters, that's a feature and it's the only way that you can encode that glyph in a VF because only offsets can be varied across variation space, not the 2x2 transforms.

**Comment by anthrotype** [comment]
> get rid of the filters that gftools sets.

doesn't gftools allow to turn them off?!

**Comment by anthrotype** [comment]
> I simply assumed that those filters are set by default in fontmake by checking the font outlines.

ok, but now I hope we both agree that they are not set by fontmake by default

**Comment by anthrotype** [comment]
no problems, glad I was able to help
