### ISSUE TITLE
The `.color` alternate glyphs from color layers should not remain in the font

### ISSUE THREAD

**Issue by vv-monsalve** [googlefonts/fontmake#1030]
When compiling a `COLR/CPAL` font, the alternate `.color` glyphs copied from the color layers in the source file are kept in the font binary after compilation. 
This is overpopulating the font with unexpected extra glyphs displayed to users in glyph panels and is reported by Fontbakery as unreachable glyphs.

**E.g. CPAL-test-2.ttf**

<img width="1160" alt="CPAL-test-2-samsa" src="https://github.com/googlefonts/fontmake/assets/48698976/87b9b345-8583-4f8f-9fd8-dacdf154c35b">

#### Sources to replicate
I made two test cases:

- `CPAL-test-font-2.glyphs` a reduced version with five glyphs of a WIP project
- `CPAL-test.glyphs` with only one glyph replication the CPAL/COLR Glyphs app tutorial 

[COLR-CPAL.zip](https://github.com/googlefonts/fontmake/files/12444079/COLR-CPAL.zip) includes the two test source files + the produced fonts

#### Build options
The fonts are successfully built with `fontmake v3.5.1` 
When using `fontmake v3.7.1` the build process fails with the following error:
````
INFO:ufo2ft:Building OpenType tables for CPALtest2-Thin
fontmake: Error: In 'CPAL-test-font-2.glyphs' -> 'master_ufo/CPALtest2.designspace': Generating fonts from Designspace failed: cannot map 'a.color0' to U+0061; already mapped to 'a'
````

PS. Let me know if this should be reported in ufo2ft instead.

**Comment by bramstein** [comment]
I think I fixed the fontmake error in https://github.com/googlefonts/glyphsLib/pull/939.

The `{glyph}.color{X}` glyphs should remain in the font as that is how the COLR specification work as far as I know. However, they should not be mapped to Unicode values.

**Comment by vv-monsalve** [comment]
> The {glyph}.color{X} glyphs should remain in the font as that is how the COLR specification work as far as I know.

Thank you @bramstein for clarifying how layers work beyond just metadata. After rereading the spec, I now understand that keeping layers allows for the repainting of glyphs.

> However, they should not be mapped to Unicode values.

Agree. But, you are already addressing this part in the Issue + PR linked above. So, closing this issue here.
