### ISSUE TITLE
--master-dir '{tmp}' while interpolating

### ISSUE THREAD

**Issue by simoncozens** [googlefonts/fontmake#1040]
For ninja reasons I need to generate instance UFOs separately and in parallel, so I am doing the equivalent of

```
$ fontmake -i "Noto Sans Hebrew ExtraLight" -o ufo -g NotoSansHebrew.glyphs --instance-dir instance_ufos/ &
$ fontmake -i "Noto Sans Hebrew Light" -o ufo -g NotoSansHebrew.glyphs --instance-dir instance_ufos/ &
$ fontmake -i "Noto Sans Hebrew Regular" -o ufo -g NotoSansHebrew.glyphs --instance-dir instance_ufos/ &
...
```

(Yes, it would be more efficient to only run `fontmake -i` once, because otherwise you're redundantly generating all the master UFOs each time. I know.)

However, even running two `fontmake -o ufo -i` in parallel leads to a race:

```
$ fontmake -i "Noto Sans Hebrew ExtraLight" -o ufo -g NotoSansHebrew.glyphs --instance-dir instance_ufos/ &; fontmake -i "Noto Sans Hebrew Light" -o ufo -g NotoSansHebrew.glyphs --instance-dir instance_ufos/
[1] 50969
INFO:fontmake.font_project:Building master UFOs and designspace from Glyphs source
INFO:fontmake.font_project:Building master UFOs and designspace from Glyphs source
INFO:glyphsLib.parser:Parsing .glyphs file
INFO:glyphsLib.parser:Parsing .glyphs file
fontmake: Error: In 'master_ufo/NotoSansHebrew-Light.ufo': Writing UFO source failed: [Errno 2] No such file or directory: 'kafrafe-hb.glif'
```

This is obviously happening because both processes are trying to write to the `master_ufo` directory at the same time.

I know, I thought; there's an option to allow temporary `master_ufo` directory. Yet:

```
$ fontmake -i "Noto Sans Hebrew Condensed Thin" --master-dir '{tmp}' -o ufo -g NotoSansHebrew.glyphs --instance-dir instance_ufos/

fontmake: error: Can't use temporary master directory with 'ufo' output
```

This error is understandable when the masters are the target of the operation; but it's less useful when the instance UFOs are the target. However, overriding the check when `args["interpolate"]` is true causes even stranger issues:

```
fontmake: Error: In 'NotoSansHebrew.glyphs' -> '../../../../../../var/folders/jp/4p0m9zvx2l739tdpflm38kv40000gn/T/master_dir_eoi2bbvr/NotoSansHebrew.designspace': Generating fonts from Designspace failed: [Errno 13] Permission denied: '/var/folders/jp/4p0m9zvx2l739tdpflm38kv40000gn/T/master_dir_eoi2bbvr/../../../../../../Users'
```

**Comment by simoncozens** [comment]
I'm not entirely clear why `fontmake -i` needs to write master UFOs *to disk* anyway.

**Comment by anthrotype** [comment]
can you try to use --output-dir instead of --instance-dir?

**Comment by anthrotype** [comment]
https://github.com/googlefonts/fontmake/blob/6a8b2907891537ce559dd3d6fcfe68d8b55d6bc9/Lib/fontmake/font_project.py#L890-L893

**Comment by simoncozens** [comment]
You're right; with a new fontmake it works fine. Thanks!
