### ISSUE TITLE
Missing X-height causes unclear crash while compiling UFO

### ISSUE THREAD

**Issue by pkolchanov** [googlefonts/fontmake#1069]
Hi!
Compiling UFOs with missing X-height metrics causes a crash with an unclear error message. It would be great to get human readable message instead. 

```bash
$ fontmake testX-Height.ufo

fontmake: Error: In 'testX-Height.ufo': Compiling UFO failed: 'h' format requires -32768 <= number <= 32767
```

Source file:
[testX-Height.ufo.zip](https://github.com/googlefonts/fontmake/files/14110167/testX-Height.ufo.zip)

**Comment by anthrotype** [comment]
but it's not missing...

It's just too large to fit a signed 16-bit integer hence the crash.

in the zip file, I see testX-Height.ufo/fontinfo.plist contains

```xml
    <key>xHeight</key>
    <real>9223372036854775808.000</real>
```

**Comment by pkolchanov** [comment]
I'm sorry!

I have no idea how I missed that :)
