### ISSUE TITLE
"Generating fonts from Designspace failed: list index out of range"

### ISSUE THREAD

**Issue by guidoferreyra** [googlefonts/fontmake#1071]
I’m trying to build a variable CFF2 font and I’m getting the following error:

```
...
INFO:fontTools.varLib:Generating HVAR
INFO:fontTools.varLib:Merging OpenType Layout tables
fontmake: Error: In 'sources/myFamily.designspace': Generating fonts from Designspace failed: list index out of range
make: *** [dev] Error 1
```

Do you have an idea what can be producing this error? The same project builds correctly as a variable ttf font.

**Comment by anthrotype** [comment]
That should not happen. Can you past the full traceback of the error with --verbose DEBUG?

**Comment by guidoferreyra** [comment]
Thanks for your help, the DEBUG command lead me to find that the problem was "open white corners" on the font.
