### ISSUE TITLE
Some instances not being processed

### ISSUE THREAD

**Issue by simoncozens** [googlefonts/fontmake#1075]
I don't understand this. With [this Glyphs file](https://github.com/googlefonts/alumni-sans-pinstripe/blob/main/sources/AlumniSansPinstripe.glyphs), I convert it to UFO, and there are instances:

```
$ grep instance master_ufo/AlumniSansPinstripe-Regular.designspace
  <instances>
    <instance name="Alumni Sans Pinstripe Regular" familyname="Alumni Sans Pinstripe" stylename="Regular" filename="../instance_ufo/AlumniSansPinstripe-Regular.ufo" stylemapfamilyname="Alumni Sans Pinstripe" stylemapstylename="regular">
    </instance>
  </instances>
```

But if I try to generate them:

```
$ fontmake -o ufo -i -m master_ufo/AlumniSansPinstripe-Regular.designspace
INFO:fontmake.font_project:Interpolating master UFOs from designspace
$ ls instance_ufo
ls: cannot access 'instance_ufo': No such file or directory
$ fontmake -o ttf -i -m master_ufo/AlumniSansPinstripe-Regular.designspace
INFO:fontmake.font_project:Interpolating master UFOs from designspace
$ ls instance_ttf
ls: cannot access 'instance_ttf': No such file or directory
```

**Comment by simoncozens** [comment]
Urgh, bad source file, ignore me. I'll try to add some better reporting for instances which were outside the designspace range.

**Comment by anthrotype** [comment]
weird, I'll take a look now

**Comment by anthrotype** [comment]
oh ok.

**Comment by simoncozens** [comment]
So the situation is that we have some old fonts which have "wrong" values for the width axis for some reason (they don't even *have* a width axis - in fact they're not even variable fonts!). So the only master is wght=400, wdth=5; I think this is an old Glyphs file where we somehow set the width value to 5 to mean "Medium (normal)". However, the *instance* is set to wght=500, wdth=100, weight class = 400, width class = 5.

wdth=100 is outside of the range 5-5 for the width "axis", so `splitInterpolable` discards it. The problem is that `splitInterpolable` is *supposed* to discard things out of scope as part of splitting DS5 into multiple subdocuments, but in this case it's a confusing thing to do.

**Comment by anthrotype** [comment]
that'd count as a source error to be honest.. I wonder if maybe splitInterpolable could pass a DS through unchanged if it can detect upfront there is nothing to be split

**Comment by anthrotype** [comment]
fontmake or fonttools could at least warn the user some of the instances are being ignored because supposedly out of bounds
