### ISSUE TITLE
Support for `public.skipExportGlyphs` in `<variable-font>` tag in Designspace files?

### ISSUE THREAD

**Issue by ryanbugden** [googlefonts/fontmake#1097]
I tried using the Designspace public key `public.skipExportGlyphs`, and those glyphs still generated with my variable font.
https://fonttools.readthedocs.io/en/latest/designspaceLib/index.html#public-skipexportglyphs

Just wondering whether this is supported and I'm doing something wrong. If not, I think it would be very useful. This is in my designspace xml:
```xml
      <lib>
        <dict>
          <key>public.fontInfo</key>
          <dict>
            <key>familyName</key>
            <string>Name Variablee</string>
          </dict>
          <key>public.skipExportGlyphs</key>
          <array>
            <string>a.ss01</string>
          </array>
        </dict>
      </lib>
```

I see mention of this public key in the [USAGE docs](https://github.com/googlefonts/fontmake/blob/fb73b7025b8f5ffebc41d10b3d485eb9b00becb7/USAGE.md?plain=1#L33), but I get the following error, because it looks like a Glyphs-specific thing.
```
fontmake: error: "--no-write-skipexportglyphs" option invalid for designspace source
```

Related issues:
- https://github.com/googlefonts/fontmake/issues/965#issue-1498322167
- https://github.com/googlefonts/fontmake/issues/343#issuecomment-525916641
- https://github.com/googlefonts/fontmake/issues/159

**Comment by anthrotype** [comment]
ufo2ft contains a bunch of tests for that as well. E.g. https://github.com/googlefonts/ufo2ft/blob/df592b17ea314e39e4434729352e4b5c8064c8da/tests/preProcessor_test.py#L377 for one involving a .designspace => VF

If I go into the ufo2ft repository directory on my local machine and try to do 

```
$ fontmake tests/data/SkipExportGlyphsTest.designspace -o variable
```

I can see that the `_stroke` glyph was excluded and the `Astroke` (`uni023A`) has been decomposed as expected.

**Comment by ryanbugden** [comment]
Hi @anthrotype thank you for your response!

I can reproduce the expected behavior on the SkipExportGlyphsTest, but I'm unable to make my own test that works. I'm probably doing something wrong.

Reproduce:
1. Download my zip [here](https://github.com/googlefonts/fontmake/files/15503516/Fontmake.Test.zip).
2. Change directories in Terminal to that folder.
3. Type `sh build-test.sh`

Outcome:
🔴 The variable font still has an `A`
🟢 The variable font has a family name of `VARIABLE TEST FAMILY NAME`
🔴 Additionally, it appears the custom designspace-specified postscriptFontName and postscriptFullName did not take.

**Comment by anthrotype** [comment]
oh I see, you have placed the public.skipExportGlyphs in the variable-font's lib, not in the global designspace lib where ufo2ft is looking. Yeah ideally each VF to be exported would have its own skipExportGlyphs. Not at the moment unfortunately. We should migrate this to ufo2ft repository. In the meantime try to move the lib key under the designspace `<lib>` element.

**Comment by anthrotype** [comment]
related https://github.com/googlefonts/ufo2ft/issues/633

**Comment by ryanbugden** [comment]
Ah that makes sense, thanks @anthrotype . Will continue there.
