### ISSUE TITLE
`public.skipExportGlyphs` works when generating individual ufo to ttf, but not when building a variable font

### ISSUE THREAD

**Issue by arrowtype** [googlefonts/fontmake#1101]
Update: I realized the solution just before filing this issue, but I’ll file it anyway, and close it, just in case someone else ends up with the same question.

[From the DesignSpace Docs](https://fonttools.readthedocs.io/en/latest/designspaceLib/index.html#public-skipexportglyphs):

> **public.skipExportGlyphs**
> This lib key works the same as the UFO lib key with the same name. The difference is that applications using a Designspace as the corner stone of the font compilation process should use the lib key in that Designspace instead of any of the UFOs. **If the lib key is empty or not present in the Designspace, all glyphs should be exported, regardless of what the same lib key in any of the UFOs says.**

(Emphasis mine). 

It is slightly strange and unexpected to me that leaving this out of the designspace would not allow the lib key of a UFO to have an effect, but it seems that FontMake is following the DS doc, so I suppose it’s not an issue here.

---

## Problem

I’ve set up `public.skipExportGlyphs` in the lib.plist of all UFOs in a designspace, so as not to export certain glyphs which are currently empty (but which may be added to in the future).

If I build any one of these UFOs directly to a TTF, using FontMake 3.9.0, the glyphs listed in `public.skipExportGlyphs` are not exported (good). However, if I build a variable font from a designspace that links all of these UFO sources, the glyphs which should be skipped are built into the resulting variable font.

I experience the problem when building directly with fontmake commands, so I don’t believe this is being caused by some fancy build process. I’ve tried this in FontMake 3.9.0, 3.7.1, and 3.4.0, and all three versions have the same issue.

I’ve removed any `lib` items from the designspace files, just to make sure those can’t be causing the problem.

~What might be causing this issue? I can probably email the font sources directly, if that would be important in debugging them.~(See update, above.)

**Comment by kontur** [comment]
Was debugging an issue between default fontmake generation and a custom setup, and this proved to the be the issue/solution. It is quite unintuitive that all UFOs having the skip key does not result in the glyphs being skipped for variable compilation. While this is according to designspace spec, maybe some preprocessing could warn about this.
