### ISSUE TITLE
GDEF without GPOS or GSUB

### ISSUE THREAD

**Issue by cmyr** [googlefonts/fontmake#1120]
In the process of investigating some diffs between `fontc` and `fontmake` I noticed that in some instances (for instance, with [Noto Hentaigana](https://github.com/notofonts/hentaigana) fontmake will produce a GDEF table (with only a GlyphClassDef subtable) even if there's no GPOS/GSUB/JSFT tables that might use anything in GDEF.

Probably the table should just be omitted in this case?

**Comment by khaledhosny** [comment]
Glyphs with mark gets their width set to zero, so that might be one legitimate use of a GDEF without other layout tables.

**Comment by cmyr** [comment]
zero'd where? They should already be zero'd in `hmtx` during compilation...

**Comment by khaledhosny** [comment]
By the layout engine (for most scripts). You might want to prevent the layout engine from zeroing them by giving the glyphs base glyph class. If the font does not have a GDEF table, some layout engine will synthesize one based on Unicode general category of the characters, which would give a different result.

It is probably a fringe use case, but I don’t see a reason why we should go out of our way to not allow it.

**Comment by cmyr** [comment]
Thinking about this more, if the glyphs get Base glyph class shouldn't they not get zero'd in hmtx? cc @dfrg @behdad, do either of you have any insight into this?

**Comment by behdad** [comment]
I'm with Khaled here. Don't speculate on what font designer is doing. For example, in Indic, often times some "Base" glyphs are zero-width. They are eg. subjoining marks, but not categorized as marks for whatever reason designer had in mind. Just don't mess with it.

**Comment by anthrotype** [comment]
> if the glyphs get Base glyph class shouldn't they not get zero'd in hmtx?

I think that's what Khaled meant. These glyphs which in absence of GDEF would otherwise be zeroed by the layout engine, are classified as bases in GDEF to prevent that from happening. I presume their hmtx advance is != 0 to begin with, otherwise why bother

**Comment by anthrotype** [comment]
also, fontmake only does the zero-ing of the hmtx advance width of glyphs categorized as non-spacing marks only for .glyphs sources to match Glyphs.app. When building from DS+UFO we do not do any of that, so the font developer can set the width as they wish in the source files, no automatic zeroing happens in the compiler (it may still occur as result of the layout engine logic that you were discussing above).

**Comment by anthrotype** [comment]
> for instance, with [Noto Hentaigana](https://github.com/notofonts/hentaigana) fontmake will produce a GDEF table (with only a GlyphClassDef subtable) even if there's no GPOS/GSUB/JSFT tables that might use anything in GDEF.

FWIW, while Noto Hentaigana has no GPOS, it does have a non-empty GSUB (I see a bunch of ligatures in there), so its GDEF might be of use there.

**Comment by dfrg** [comment]
+1 to everything above. Don’t mess with hmtx outside of Glyphs app expectations. It also seems to me that GDEF is dead weight if no other layout tables are present.

**Comment by cmyr** [comment]
> +1 to everything above. Don’t mess with hmtx outside of Glyphs app expectations. It also seems to me that GDEF is dead weight if no other layout tables are present.

To clarify here, nobody is suggesting messing with hmtx, this issue is really about whether or not to include a GDEF table if we don't have other layout tables.

**Comment by dfrg** [comment]
Are there any layout engines that, in the absence of GSUB/GPOS, will attempt fallback shaping using GDEF to zero advance widths of marks? Does HB do this?

**Comment by behdad** [comment]
> Are there any layout engines that, in the absence of GSUB/GPOS, will attempt fallback shaping using GDEF to zero advance widths of marks? Does HB do this?

Yes, HB does. Grep for `HB_OT_SHAPE_ZERO_WIDTH_MARKS_BY_GDEF`.

**Comment by cmyr** [comment]
> > Are there any layout engines that, in the absence of GSUB/GPOS, will attempt fallback shaping using GDEF to zero advance widths of marks? Does HB do this?
> 
> Yes, HB does. Grep for `HB_OT_SHAPE_ZERO_WIDTH_MARKS_BY_GDEF`.

Where I'm confused here is that (at least in the case of fontmake/fontc) if the mark is going to end up in the Marks category in GDEF than it will be zero'd in hmtx, so this would be irrelevant?

I guess the case where this might be an issue is if a glyph that _would_ be inferred to be nonspacing is explicitly marked as a base in GDEF, in which case HB would know to not zero it?


(I guess my real question is why not trust the values in hmtx?)

**Comment by behdad** [comment]
The real answer is: historical reasons. Or rather: Windows does that.

**Comment by anthrotype** [comment]
> if the mark is going to end up in the Marks category in GDEF than it will be zero'd in hmtx

only for Glyphs sources, to match Glyphs.app's behavior
