### ISSUE TITLE
Anchors issue - related to 'Shapes languages in all GF glyphsets' fb check

### ISSUE THREAD

**Issue by emmamarichal** [googlefonts/fontmake#1137]
Hello!

cc @simoncozens @vv-monsalve 
I post the issue here, since I have the same result with `gftools builder`, but a different one by exporting from Glyphs.

This concern the fail: `🔥 FAIL Shapes languages in all GF glyphsets`.

When I export the font from Glyphs, this is the list I got:

<details>
    <summary>🔥 <b>FAIL</b> Shapes languages in all GF glyphsets. <a href="https://fontbakery.readthedocs.io/en/stable/fontbakery/checks/vendorspecific.googlefonts.glyphset.html#"></a></summary>
    <div>
* 🔥 **FAIL** <p>GF_Phonetics_SinoExt glyphset:</p>
<table>
<thead>
<tr>
<th align="left">FAIL messages</th>
<th align="left">Languages</th>
</tr>
</thead>
<tbody>
<tr>
<td align="left">The locl feature did not affect Eng</td>
<td align="left">bm_Latn (Bambara), dyu_Latn (Dyula), ig_Latn (Igbo), lg_Latn (Ganda), mua_Latn (Mundang), bqv_Latn (Koro Wachi), lia_Latn (Limba, West-Central), gng_Latn (Ngangam), kyf_Latn (Kouya), bsc_Latn (Bassari) and 241 more.</td>
</tr>
<tr>
<td align="left">Shaper didn't attach uni0328.case to uni018F</td>
<td align="left">gkp_Latn (Kpelle, Guinea), gkp_Latn (Kpelle, Guinea), gkp_Latn (Kpelle, Guinea), gkp_Latn (Kpelle, Guinea), gkp_Latn (Kpelle, Guinea) and gkp_Latn (Kpelle, Guinea)</td>
</tr>
<tr>
<td align="left">Shaper didn't attach uni0328 to uni025B</td>
<td align="left">gkp_Latn (Kpelle, Guinea), gkp_Latn (Kpelle, Guinea) and gkp_Latn (Kpelle, Guinea)</td>
</tr>
<tr>
<td align="left">Shaper didn't attach uni0328.case to uni0190</td>
<td align="left">gkp_Latn (Kpelle, Guinea), gkp_Latn (Kpelle, Guinea), gkp_Latn (Kpelle, Guinea), gkp_Latn (Kpelle, Guinea), gkp_Latn (Kpelle, Guinea) and gkp_Latn (Kpelle, Guinea)</td>
</tr>
<tr>
<td align="left">Shaper didn't attach uni0328 to uni0254</td>
<td align="left">gkp_Latn (Kpelle, Guinea), gkp_Latn (Kpelle, Guinea) and gkp_Latn (Kpelle, Guinea)</td>
</tr>
<tr>
<td align="left">Shaper didn't attach uni0328.case to uni0186</td>
<td align="left">gkp_Latn (Kpelle, Guinea), gkp_Latn (Kpelle, Guinea), gkp_Latn (Kpelle, Guinea), gkp_Latn (Kpelle, Guinea), gkp_Latn (Kpelle, Guinea) and gkp_Latn (Kpelle, Guinea)</td>
</tr>
<tr>
<td align="left">Shaper didn't attach uni0328.smcp to uni0259.smcp</td>
<td align="left">gkp_Latn (Kpelle, Guinea), gkp_Latn (Kpelle, Guinea) and gkp_Latn (Kpelle, Guinea)</td>
</tr>
<tr>
<td align="left">Shaper didn't attach uni0328.smcp to uni025B.smcp</td>
<td align="left">gkp_Latn (Kpelle, Guinea), gkp_Latn (Kpelle, Guinea) and gkp_Latn (Kpelle, Guinea)</td>
</tr>
<tr>
<td align="left">Shaper didn't attach uni0328.smcp to uni0254.smcp</td>
<td align="left">gkp_Latn (Kpelle, Guinea), gkp_Latn (Kpelle, Guinea) and gkp_Latn (Kpelle, Guinea)</td>
</tr>
<tr>
<td align="left">Shaper didn't attach acutecomb.smcp to uni028A.smcp</td>
<td align="left">tcd_Latn (Tafi) and blo_Latn (Anii)</td>
</tr>
<tr>
<td align="left">Shaper didn't attach tildecomb.smcp to uni028A.smcp</td>
<td align="left">tcd_Latn (Tafi), tcd_Latn (Tafi), tcd_Latn (Tafi) and biv_Latn (Birifor, Southern)</td>
</tr>
<tr>
<td align="left">Shaper didn't attach uni0304.smcp to uni028A.smcp</td>
<td align="left">tcd_Latn (Tafi)</td>
</tr>
<tr>
<td align="left">Shaper didn't attach uni030C.smcp to uni028A.smcp</td>
<td align="left">tcd_Latn (Tafi)</td>
</tr>
<tr>
<td align="left">Requires Small-cap: ǰ; both buffers returned uni01F0=0+432</td>
<td align="left">taq_Latn (Tamasheq, Latin) and ttq_Latn (Tawallammat Tamajaq)</td>
</tr>
<tr>
<td align="left">Requires Small-cap: ẖ; both buffers returned uni1E96.varAlt01=0+758</td>
<td align="left">udu_Latn (Uduk)</td>
</tr>
<tr>
<td align="left">Shaper didn't attach gravecomb.smcp to uni028A.smcp</td>
<td align="left">blo_Latn (Anii)</td>
</tr>
<tr>
<td align="left">Shaper didn't attach uni0302.smcp to uni028A.smcp</td>
<td align="left">blo_Latn (Anii)</td>
</tr>
<tr>
<td align="left">The locl feature did not affect uni028B</td>
<td align="left">tod_Latn (Toma)</td>
</tr>
<tr>
<td align="left">Requires Small-cap: ɪ; both buffers returned uni026A=0+442</td>
<td align="left">kzc_Latn (Bondoukou Kulango)</td>
</tr>
<tr>
<td align="left">Requires Small-cap: ʘ; both buffers returned uni0298=0+776</td>
<td align="left">ngh_Latn (Nǁng)</td>
</tr>
<tr>
<td align="left">Requires Small-cap: ꟈ; both buffers returned uniA7C8=0+692</td>
<td align="left">mor_Latn (Moro)</td>
</tr>
<tr>
<td align="left">Some mark glyphs were missing: ◌̛</td>
<td align="left">vi_Latn (Vietnamese)</td>
</tr>
</tbody>
</table>
 [code: failed-language-shaping]

* ⚠️ **WARN** <p>GF_Phonetics_SinoExt glyphset:</p>
<table>
<thead>
<tr>
<th align="left">WARN messages</th>
<th align="left">Languages</th>
</tr>
</thead>
<tbody>
<tr>
<td align="left">No exemplar glyphs were defined for language Mina</td>
<td align="left">hna_Latn (Mina)</td>
</tr>
<tr>
<td align="left">No exemplar glyphs were defined for language Amo</td>
<td align="left">amo_Latn (Amo)</td>
</tr>
<tr>
<td align="left">No variant glyphs were found for uni01A9</td>
<td align="left">gaa_Latn (Ga)</td>
</tr>
<tr>
<td align="left">No variant glyphs were found for uni01B7</td>
<td align="left">gaa_Latn (Ga)</td>
</tr>
<tr>
<td align="left">No exemplar glyphs were defined for language Eastern Gurung, Latin</td>
<td align="left">ggn_Latn (Eastern Gurung, Latin)</td>
</tr>
<tr>
<td align="left">No exemplar glyphs were defined for language Mbunga</td>
<td align="left">mgy_Latn (Mbunga)</td>
</tr>
<tr>
<td align="left">No variant glyphs were found for uni0181</td>
<td align="left">dnj_Latn (Dan)</td>
</tr>
<tr>
<td align="left">No variant glyphs were found for uni01B2</td>
<td align="left">tod_Latn (Toma)</td>
</tr>
<tr>
<td align="left">No exemplar glyphs were defined for language Koro</td>
<td align="left">kfo_Latn (Koro)</td>
</tr>
<tr>
<td align="left">No exemplar glyphs were defined for language Seki</td>
<td align="left">syi_Latn (Seki)</td>
</tr>
<tr>
<td align="left">No exemplar glyphs were defined for language Atsam</td>
<td align="left">cch_Latn (Atsam)</td>
</tr>
</tbody>
</table>
 [code: warning-language-shaping]

</div>
</details>

But, when exporting with fontmake or gftools builder, I got a very long list I can't even copy/paste here.
-> [report.md.zip](https://github.com/user-attachments/files/17961336/report.md.zip)

The file has some complex anchors like this, but even if I simplify them, it doesn't solve the fail.

![Image](https://github.com/user-attachments/assets/a6c26d6e-a42b-4667-9929-7caf42850419)

### Here you can find:

- Exported from Glyphs: [Playfair_Glyphs.zip](https://github.com/user-attachments/files/17961380/Playfair_Glyphs.zip)
- Exported with gftools builder: [Playfair_builder.zip](https://github.com/user-attachments/files/17961371/Playfair_builder.zip)

**Comment by simoncozens** [comment]
This looks like a bug in the font sources.

When we compile a font we have some features - `kern`, `dist`, `mark`, `mkmk`, `abvm`, `blwm` - which are not normally written explicitly as feature code. Normally, we generate these features from the kerning tables and anchors in the font sources. So the question is, what happens if you want the attachment rules from the anchors *and* you want to write your own attachment rules?

The way ufo2ft/fontmake works is that if you provide your own "manual" feature code for any of these features, this is used instead of the automatically generated code. If you want to use both the data from the anchors in the glyphs and *also* manual feature code, you need to ask for it. So in your `kern`, `mark` and `mkmk` features, write this:

```
# Automatic Code Start
```

e.g. in `mark`:

```
# Automatic Code Start

pos @afrcNumerators' lookup MARK_LKP_1 @afrcBars @afrcDenominators @afrcDenominators @afrcDenominators @afrcDenominators @afrcDenominators @afrcDenominators @afrcDenominators @afrcDenominators @afrcDenominators @afrcDenominators;
```

This will tell fontmake where to place the automatically generated rules. (Because you might want the automatic rules before or after your manual rules.)

**Comment by emmamarichal** [comment]
@simoncozens Ok I see, thank you! I'll try this 👌
