### ISSUE TITLE
Generating instances from glyphspackage file don't work

### ISSUE THREAD

**Issue by iyadh** [googlefonts/fontmake#1138]
Hi,

I'm trying to generate production files (basically variable TTF, and OTFs) from a glyphspackage file. Generating a variable TTF works perfectly (but seems to omit _segment.strokebutt segment component), but it does not generate any file when it comes to OTFs. I tried the same thing with a glyphs file, but no success. If I remove `-i` flag, it generates OTFs from masters.
The output for this command `fontmake -g ./src/my-font.glyphspackage -i -o otf`

```
INFO:fontmake.font_project:Building master UFOs and designspace from Glyphs source
INFO:glyphsLib.parser:Parsing .glyphs file
INFO:glyphsLib.builder:Running 'propagate_all_anchors' transformation
INFO:fontmake.font_project:Loading 8 DesignSpace source UFOs
INFO:fontmake.font_project:Interpolating master UFOs from designspace
```

My glyphs file has 3 axis (one is a virtual master), variable export, 18 instances.

Any suggestions?

Thanks in advance

**Comment by khaledhosny** [comment]
Is this the full log output you get? Can you check the generated DesignSpace file (you might need to run `fontmake -g ./src/my-font.glyphspackage -o ufo` to get one), does it have any `instance` elements?

**Comment by iyadh** [comment]
Yes, that's the full output I get.
I checked the designspace file, I got this as output:
```
INFO:fontmake.font_project:Building master UFOs and designspace from Glyphs source
INFO:glyphsLib.parser:Parsing .glyphs file
INFO:glyphsLib.builder:Running 'propagate_all_anchors' transformation
INFO:fontmake.font_project:Saving master_ufo/MyFont.designspace
INFO:fontmake.font_project:Saving master_ufo/MyFont-Light.ufo
INFO:fontmake.font_project:Saving master_ufo/MyFont-Bold.ufo
INFO:fontmake.font_project:Saving master_ufo/MyFont-DisplayLight.ufo
INFO:fontmake.font_project:Saving master_ufo/MyFont-DisplayBold.ufo
INFO:fontmake.font_project:Loading 8 DesignSpace source UFOs
```
The designspace file has all the instances from the original Glyphs file as shown in the following screenshot:

![Image](https://github.com/user-attachments/assets/3049be31-ab9a-4a47-b77d-6d2d965abec0)

**Comment by iyadh** [comment]
The issue was regarding virtual axis configuration in instances. That was set to zero, which appears to be wrong and should take a value. Once updated, fontmake did generate the instances.
