### ISSUE TITLE
Accommodate for CFF2 variable fonts

### ISSUE THREAD

**Issue by behdad** [googlefonts/fontmake#183]
Can we add:

  - otf-interpolatable output; Disables overlap removal, and when we have CFF operator specializer, disables that too,

  - otf-variable.  This is blocked by fonttools supporting CFF2 varfonts, but will be coming.

  - Also add ttf-variable to go with it.  I'm fine with keeping variable a synonym for ttf-variable.

Would have been nice if the output dirs didn't use underscore instead of dash, but that's bikeshedding.

**Comment by madig** [comment]
CFF2 VFs are supported.
