### ISSUE TITLE
AutomatedTestReport: CFFContours do not have correct winding direction

### ISSUE THREAD

**Issue by marekjez86** [googlefonts/fontmake#21]
I copied the text below from an email by Jelle.B who looked at regular Ethiopic font (see the otf file in the attached zip) generated by the pipeline from the glyphs file (see the attached zip) on about 1/Feb/2016. The comments pertain to that version of the pipeline. See the bottom of this message for the reason why I cannot generate a new version of the fonts.

'Of the errors listed by our test tool I mention:
CFFContours do not have correct winding direction. 32 more like this [marekjez86: repeats 32 times]'

[NotoSansEthiopicCondensed-Regular-km-error.zip](https://github.com/googlei18n/fontmake/files/133281/NotoSansEthiopicCondensed-Regular-km-error.zip)

Note that NotoSansEthiopic-MM.glyphs generates as of 12/Feb/2016 "defcon.errors.DefconError: The kerning data is not valid" so I cannot check what the newest version of pipeline generates (see https://github.com/googlei18n/fontmake/issues/13 )

**Comment by behdad** [comment]
We should make ufo2ft fix contour direction for both CFF and TrueType.

That said, since we are interpolating and building GX fonts, etc, we should expect Noto source Glyphs files to always have uniform contour directions.  I think we should start having a lint tool that operates on the Glyphs source (converted to UFO), instead of checking the binary output of our pipeline.

**Comment by davelab6** [comment]
> a lint tool that operates on the Glyphs source (converted to UFO)

Linting the UFO precludes autofix methods which seem undesirable to me; why not lint the Glyphs source itself?

**Comment by behdad** [comment]
> a lint tool that operates on the Glyphs source (converted to UFO)
> 
> Linting the UFO precludes autofix methods which seem undesirable to me; why not lint the Glyphs source itself?

We are less interested in autofixing the source.

**Comment by madig** [comment]
How to reliably detect the wrong winding order when overlaps and multiple contours are involved? Unless the algorithm is robust, autofixing at the ufo2ft level seems... adventurous to me.

**Comment by marekjez86** [comment]
I don't think we should autofix anything (i.e., I'd like to see an error and make it up to the user to fix it). IMHO we can close it.
