### ISSUE TITLE
Overlap removal for ttf-interpolatable?

### ISSUE THREAD

**Issue by madig** [googlefonts/fontmake#430]
Is this possible/sensible from an algorithmic standpoint? We currently waste some time on making interpolatable TTFs with removed overlaps... by hand.

**Comment by anthrotype** [comment]
it's ... hard.

**Comment by behdad** [comment]
> Is this possible/sensible from an algorithmic standpoint?

Not really. And it can and does change the interpolation result.

> We currently waste some time on making interpolatable TTFs with removed overlaps... by hand.

Why?

**Comment by behdad** [comment]
There shouldn't be any reasonable backward-compat needs with overlaps in TrueType outlines.

**Comment by behdad** [comment]
To correct myself, considering the flag that Apple uses...
