### ISSUE TITLE
Better exception when attempting to gen designspace instances

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/fontmake#449]
I attempted to generate static ttf instances for [RobotoVF](https://github.com/TypeNetwork/Roboto), using its [min designspace](https://github.com/TypeNetwork/Roboto/blob/master/Roboto-min.designspace), with the following command:

```
fontmake -m Roboto-min.designspace -i -o ttf --no-production-names
```

It produced the following traceback.

```
    instancePath = os.path.join(os.path.dirname(self.path), filename)
  File "/Users/marc/Documents/googlefonts/manual_font_cleaning/_privates/Roboto/env/lib/python2.7/posixpath.py", line 68, in join
    if b.startswith('/'):
AttributeError: 'NoneType' object has no attribute 'startswith'
```

According to the designspace repo [README](https://github.com/LettError/designSpaceDocument#4-instance-element),  an instance filename is required in order for this to work for static ttfs (it doesn't need a filename if used as an instance in a variable font)

The Roboto min designspace doesn't specify filenames for instances (it's meant to be a VF).

```
        <instance familyname="Roboto" stylename="Black Italic">
            <location>
                <dimension name="width" xvalue="100" />
                <dimension name="slant" xvalue="12" />
                <dimension name="weight" xvalue="1.125000" />
            </location>
            <kerning />
            <info />
        </instance>
```

Could we have a more meaningful exception to catch this?

**Comment by anthrotype** [comment]
well, technically that line comes from mutatorMath so this should probably be handled there.

though, looking at your traceback, it's strange that `os.path.join` is the one failing when given a self.path=None; I would have expected `os.path.dirname` to be failing with some TypeError since the latter is evaluated before the former... :thinking:

**Comment by anthrotype** [comment]
or is that line coming from `fonttools.designspaceLib`? You only pasted the last few lines and it's not clear where the error is originating from. I'll double check, but sure we could prevent this from happening and throw a more meaningful message to the user.

**Comment by madig** [comment]
Fontmake 2.0.0 will generate a filename if one doesn't exist, provided you use the default instantiator instead of the DS reader in MutatorMath (`--use-mutatormath`).

**Comment by madig** [comment]
Actually, I lied. It does output a better message now though, when the new Instantiator is used:

```
> fontmake -m .\src\Cantarell.designspace -i -o otf
[... stack trace ...]
ValueError: It is currently required that instances have filenames set.
```
