### ISSUE TITLE
Feature request: ignore non-exporting glyphs from Glyphs files

### ISSUE THREAD

**Issue by laerm0** [googlefonts/fontmake#542]
In Glyphs.app, you can set glyphs to non-exporting. If there are some issues with these glyphs, Glyphs doesn't care upon export. Fontmake, however, works on the entire file. Can we have an `--ignore-nonexporting` option for Glyphs input?

**Comment by madig** [comment]
The ground work for this has been done, now glyphsLib needs to learn about the new `public.skipExportGlyphs` property. fontmake will then do the right thing without any switch.

https://github.com/googlei18n/glyphsLib/issues/515

**Comment by laerm0** [comment]
Great, thanks @madig !

**Comment by madig** [comment]
I think this is now the default behavior in fontmake 2.0.
