### ISSUE TITLE
is this an issue?

### ISSUE THREAD

**Issue by laerm0** [googlefonts/fontmake#548]
When exporting Open Sans (as we were talking about in https://github.com/laerm0/opensans/issues/8) to UFO using `fontmake -g OpenSans-Roman-no_brackets.glyphs -o ufo`, I get a lot of errors on kerning pairs.

```
WARNING:glyphsLib.builder.builders.UFOBuilder:Non-existent glyph class public.kern2.v found in kerning rules.
WARNING:glyphsLib.builder.builders.UFOBuilder:Non-existent glyph class public.kern2.y found in kerning rules.
WARNING:glyphsLib.builder.builders.UFOBuilder:Non-existent glyph class public.kern2.ustraitstroke-cy found in kerning rules.
WARNING:glyphsLib.builder.builders.UFOBuilder:Non-existent glyph class public.kern2.v found in kerning rules.
WARNING:glyphsLib.builder.builders.UFOBuilder:Non-existent glyph class public.kern2.y found in kerning rules.
```

etc

Is this actually an error? The source file does have these classes; it looks like UFO output has these classes as well.

**Comment by anthrotype** [comment]
the warning is telling you that those kerning groups are missing. They are used in the kerning pairs, but the groups are not there. I downloaded the .glyphs file and opened in Glyphs.app and I can see that those glyphs have no {left,right}KerningGroup assigned.

**Comment by madig** [comment]
I have been stumped by this warning before, it would probably be clearer as "Kerning pair (x, y) is referencing a kerning class x which is not defined.".
