### ISSUE TITLE
fontmake should use ttfautohint-py wrapper

### ISSUE THREAD

**Issue by anthrotype** [googlefonts/fontmake#562]
https://github.com/fonttools/ttfautohint-py

and should remove that `fontmake/ttfautohint.py` module

**Comment by hyvyys** [comment]
Not sure if related, I get this

```'../../../../../../tmp/tmprxum4866.ttf': Could not launch ttfautohint (is it installed?): [Errno 2] No such file or directory: 'ttfautohint': 'ttfautohint'```

And fontmake is unable to hint the fonts.
