### ISSUE TITLE
Common confusion: why can't a designspace set axis defaults which are not aligned to sources / masters?

### ISSUE THREAD

**Issue by thundernixon** [googlefonts/fontmake#566]
A question frequently comes up when fontmake users are building variable fonts from a designspace: why does there need to be a `source` at the default location? 

A common scenario: a designer makes a Light and a Bold master, but thinks of "Regular" as being the default weight. So, their designspace looks something like this:

```
<axis tag="wght" name="Weight" minimum="300" maximum="700" default="400">

<!-- source at wght=300 -->

<!-- source at wght=700 -->

<!-- instances -->
```

The user gets an error such as:

```
ufo2ft.errors.InvalidDesignSpaceData: Can't find base (neutral) master in DesignSpace document
```

Of course, the easy answer is for the user to set each axis default to something represented by one of my sources. However, this question keeps coming up (two separate people asked about it on channels I'm in today), and I don't have an answer to point to to justify this approach. I have dug around, but can't find an authoritative resource / issue / spec to point to in order to explain _why_ this is a source is required at the default location.

Here's my best guess: it's logical that the default of each axis must be in a source, because...

1. Variable fonts work by adding new tables to the OpenType font file. Legacy software can still render the default master, because its coordinates are still represnted in old tables like GLYF, the same as fonts before. Legacy software is the main place the default axis values matter for, but by the nature of them being unable to interpret new tables, legacy apps can't compute a default instance from fvar infomation – it just ignores that.

2. If you didn't supply a source with defaults but still expected the designspace to build, that would probably mean that fontmake/varLib would have to pre-interpolated that set of default coordinates and other data to populate the old tables for legacy software.

3. If fontmake/varLib _did_ calculate the default master for you and insert this in the old tables, your file would be just as heavy as if you had pre-calculated that extra source file yourself (e.g. used "Instance as Master" in GlyphsApp). So, those projects would have more code to write and support, without an actual benefit to the resulting font files. In fact, making it more convenient to make axis defaults that were not part from a source would probably lead to many more VFs that were bigger than desired, because font makers wouldn't run into this issue, and many fonts would silently gain extra sets of deltas in the fvar table, mostly to support legacy software.

---

Of course, I think part of this confusion is driven by people have the expectation that _of course_ `400` / Regular should be the default weight for a font, and of course it seems that this should be the initial value an end-user sees when they pull up a variable font's in Illustrator, et al, as the initial state of the axis sliders.

Is my guess correct about the reason for requiring a source at the default location, or not? Am I saying something inaccurate or missing something? _IS_ it possible to create a default axis value without adding a new source or file weight to built fonts?

Thanks for any insights on this!

**Comment by thundernixon** [comment]
This received some good conversation at https://twitter.com/arrowtype/status/1157396110505381889?s=21. More comments are welcome, but I feel like the question is answered.

Simply put, my guess above is correct overall, if verbose. 

A variable font needs to get its glyf table data from somewhere to support software that can't read the fvar table, and there would be file size drawbacks (and possibly unexpected outcomes) if FontMake generated the glyf table data from inputs. 

Still, from a user experience point of view, it might be nice for the making and usage of variable fonts to be less tied to technical limitations and more on user expectations, so potentially this would be a good thing to solve for.

Comments are still welcome, but I'll close this, as I feel like I understand this now.

**Comment by madig** [comment]
I think the primary reason is "2.", followed by "3.". No one has done the work of pre-interpolating a Designspace in this regard.

You can write a script that takes a DS, generates an instance at the location of your choosing and reinserts it as a master, all in-memory. Have a look at fontmake's new [instantiator.py](https://github.com/googlefonts/fontmake/blob/master/Lib/fontmake/instantiator.py).

**Comment by tphinney** [comment]
Yes, but...

The default master MUST be accessible by orthogonal move(s) to the other axis-defining masters. This means that, unless it is a single-axis font, it could mean adding a LOT of masters.

Example: have a square designspace defined by masters in four corners. Putting the default somewhere in the middle requires adding FIVE masters—more than you started with! And it gets worse if you have more axes.

Leastways, that’s my understanding.

**Comment by behdad** [comment]
> Yes, but...
> 
> The default master MUST be accessible by orthogonal move(s) to the other axis-defining masters. This means that, unless it is a single-axis font, it could mean adding a LOT of masters.
> 
> Example: have a square designspace defined by masters in four corners. Putting the default somewhere in the middle requires adding FIVE masters—more than you started with! And it gets worse if you have more axes.
> 
> Leastways, that’s my understanding.

Exactly.
