### ISSUE TITLE
Unusual metrics adjustments from Glyphs source with intermediate masters

### ISSUE THREAD

**Issue by yanone** [googlefonts/fontmake#569]
I have a Glyphs source with four masters: https://github.com/xotypeco/big_shoulders/blob/master/source/Big%20Shoulders.glyphs

Generating interpolated instances that are under influence of intermediate masters (Glyphs’ "brace layers") show anomalies in metrics: Many composed glyphs show an increase in their right sidebearing. See `diffenator` output below.

The affected glyphs (example: `Ndotbelow`) are themselves not under influence of brace layers, which are the typical `a`, `e`, etc in this font. This happens when the entire font is under influence of interpolation that needs to regard brace layers.
However, not all composed glyphs are affected. I can’t see a pattern.
What I can see is that the accents involved show a zero-width in the fontmaked file while they have positive sidebearings in the source. Now sure if this is related.

Instances that sit directly on masters (Thin, Black) are not affected. 

Also not affected is the same instance generated by the same source but without any brace layers (deleted all brace layers for comparison). That narrows down the culprit quit a bit.

The above happens identically in 2.0.0b1 and 1.10.1, despite the outline interpolation being fixed in 2.0.0b1 that involves brace layers.

Below is the output of the fontmaked file (new) against the Glyphs-generated file (old) like so: `diffenator glyphsmaked.ttf fontmaked.ttf`.

The lowest-most lines with a `1.0` difference are probably rounding errors and personally I don't mind them for a normal text font.

```
****metrics modified: 63****

glyph               diff_adv            
uni01CA             25.0                
uni1E43.sc          21.0                
Ncaron              13.0                
uni1E46             13.0                
Wgrave              13.0                
uni1E44             13.0                
Ydieresis           13.0                
uni0232             13.0                
Jcircumflex         13.0                
Wacute              13.0                
uni1EF8             13.0                
Yacute              13.0                
uni0145             13.0                
Ntilde              13.0                
Wdieresis           13.0                
uni1EF4             13.0                
uni1E48             13.0                
Ygrave              13.0                
Nacute              13.0                
uni1EF6             13.0                
Wcircumflex         13.0                
uni1E8E             13.0                
uni01CB             13.0                
Ycircumflex         13.0                
uni01C7             12.0                
wcircumflex.sc      10.0                
wgrave.sc           10.0                
wdieresis.sc        10.0                
wacute.sc           10.0                
uni1EF7             5.0                 
uni1E47.sc          5.0                 
uni0233             5.0                 
nacute.sc           5.0                 
uni1E45.sc          5.0                 
yacute              5.0                 
uni1E49.sc          5.0                 
ntilde.sc           5.0                 
ycircumflex         5.0                 
uni1EF5             5.0                 
uni1E8F             5.0                 
uni0146.sc          5.0                 
ygrave              5.0                 
uni01CC.sc          5.0                 
uni1EF9             5.0                 
ydieresis           5.0                 
ncaron.sc           5.0                 
uni1E42             3.0                 
Ohorn               1.0                 
uni01C4             1.0                 
seveneighths        1.0                 
onequarter          1.0                 
fi                  1.0                 
oslashacute         1.0                 
uni2153             1.0                 
uni1EDC             1.0                 
uni1EDE             1.0                 
uni01C5             1.0                 
uni1EE0             1.0                 
Oslashacute         1.0                 
aeacute             1.0                 
uni1EE2             1.0                 
uni1EDA             1.0                 
oneeighth           1.0 
```

**Comment by madig** [comment]
Do these diffs also occur when generating a variable font? Which instance was used to compute the diffs?

**Comment by madig** [comment]
I can confirm a 10 fU diff of the RSB for Text Regular "Ǌ" between the Glyphs.app export and a v2.0-dev generated one. There also seems to be a barely visible diff (1 fU?) between a v2.0-dev generated instance and the same instance of a VF, at least with Firefox on Windows 10 1903.

**Comment by madig** [comment]
I see a possible pattern. The glyphs that yanone listed that have a diff > 1 fU are (almost all?) components of glyphs that have intermediate masters. Maybe something does not consider them in the interpolation when given them as components as opposed as when gven them as outlines. Or something.

**Comment by madig** [comment]
When I change the RSB of the "N" brace layer (in Text Thin) to the original interpolated value (roughly -13 fU or something) and interpolate the Text Regular instance in Glyphs, I get the value that fontmake outputs. So it really seems to be that the increased RSB of the brace layer puts a kink in the metrics interpolation, so technically, all glyphs that use "N" and other braced glyphs as components need to have brace layers at the same location that carry the braced offsets etc.

**Comment by madig** [comment]
@schriftgestalt What you say about this?

**Comment by anthrotype** [comment]
> technically, all glyphs that use "N" and other braced glyphs as components need to have brace layers at the same location that carry the braced offsets

correct. And I don't believe this can be automated in a way that can be generalised to all kinds of composite glyphs. Perhaps only for composite glyphs that use auto-alignment..

**Comment by yanone** [comment]
FYI, 
I wrote [this Glyphs script](https://github.com/yanone/Yanone-GlyphsApp-Scripts/blob/master/Interpolation/Expand%20Intermediate%20Masters.py) to convert all brace layers into fully expanded masters as a workaround to create correct static instances, if anyone needs it.

**Comment by madig** [comment]
Thanks! I discussed this with @anthrotype and we decided that it would be best to simply detect this situation and warn the user, but not try to be smart from within glyphsLib.

**Comment by schriftgestalt** [comment]
I just tried that in Glyphs and as long as you use automatic alignment, it exports correct (for static instances at least). 
And I don’t think it needs a full master to fix the brace layers, adding a brace layer in the components glyphs should be enough.

**Comment by anthrotype** [comment]
Yes, you don't need to expand the brace layers into font-wide masters (which loses all the benefits of sparse intermediate masters).
You only need to do that for any composite glyphs whose components' base glyph use brace layers, as well as for all the other components' base glyphs which do not have brace layers.

For example, for your "NJ" composite glyph, where the "N" glyph has brace layers, but "NJ" and "J" do not:
1) in the "NJ" composite glyph, you make a copy of the master layers and rename them to the brace layers' name of the "N" glyph;
2) in the "J" outline glyph, similarly you duplicate the master layers and rename them as the brace layers, then you right-click on  "Re-interpolate" to get the correct interpolated outline (and do not retouch it afterwards).

I tried this workaround on a couple of affected composite glyphs in BigShoulders font and I can confirm that it is working as expected when building static instances or variable font using fontmake.

**Comment by yanone** [comment]
Awesome, thank you.
Guess I’ll make a script then that automatically creates the brace layers in the composite glyphs :)

So this sounds like a general conduct to produce VF with brace layers. This should be more widely known.

@schriftgestalt, again the question: Does Glyphs take care of this automatically when exporting VF? Sounds like you should look into this for your own purpose.

**Comment by anthrotype** [comment]
yes, ideally glyphsLib would take care of that automatically. However the problem is understanding how exactly automatic alignment of composite glyphs is implemented in Glyphs.app.

**Comment by schriftgestalt** [comment]
This is not handled properly for variable font export, yet.

**Comment by yanone** [comment]
I wrote the correct script to handle this issue: [Create Missing Brace Layers in Components.py](https://github.com/yanone/Yanone-GlyphsApp-Scripts/blob/master/Interpolation/Create%20Missing%20Brace%20Layers%20in%20Components.py)

We’ll accept (for now) that VF sources need to be prepared accordingly.
I’m closing this. Thanks guys.
