### ISSUE TITLE
Fontmake to use preferred font name from Glyphs source (or --family-name) as static font’s names

### ISSUE THREAD

**Issue by yanone** [googlefonts/fontmake#570]
I can’t get `fontmake` to use the intended family/font names.

I have a two-axis Glyphs source (family name: `Big Shoulders`) with instances defined containing the optical size in the instance name: `Text Regular` and `Display Regular`, for example.

I need the resulting family name to be `Big Shoulders Text` and `Big Shoulders Display`, effectively leading to PostScript names of `BigShouldersText-Regular` and `BigShouldersDisplay-Regular`.

Using `fontmake` without `--family-name` leads to fonts being called `BigShoulders-TextRegular`, despite the Glyphs source having the intended names defined in the instances’  respective `WWSFamilyName`/`WWSSubfamilyName`/`preferredFamilyName`/`preferredSubfamilyName` custom parameters. Could they maybe be used when present?

Otherwise, calling `fontmake` using `--family-name "Big Shoulders Text"` leads to no font being maked, unfortunately, with the last two output lines being:
```
INFO:fontmake.font_project:Interpolating master UFOs from designspace and applying instance data
DEBUG:fontmake.timer:Took 0.000s to run 'save_otfs'
```

So it feels like `fontmake` doesn’t know what font to compile.

**Comment by anthrotype** [comment]
try to call the instances just "Regular" and use the `familyName` instance custom parameter to differentiate the two: e.g. in one you write "Big Shoulder Text" and in the other "Big Shoulders Display". That is how the "UI" variants in NotoSans are differentiated.

I can't check right now, but I think the custom parameters you mentioned should be supported if there are equivalent fontinfo.plist entries to covert them to (glyphsLib takes care of translating those, and ufo2ft uses the equivalent UFO fontinfo attributes to generate a name table).

@madig can you please take a look?

**Comment by yanone** [comment]
This works nicely. Thank you.

**Comment by madig** [comment]
I looked at the .glyphs file, specifically Text Thin. When glyphs2ufo-ing, the desired naming custom parameters are written to the Designspace file and fontmake 2.0.0b1 picks them up and writes them into the interpolated UFO. The final instance TTF seems to carry the desired name sin the name table. So... it seems to work?

**Comment by yanone** [comment]
Thanks. I'm using the `familyName` custom parameter now, which works nicely.
