### ISSUE TITLE
Instance generation: warn when default font contains font info entries that are instance-specific and are not overridden in the Designspace instance attributes

### ISSUE THREAD

**Issue by madig** [googlefonts/fontmake#574]
I recently debugged a release where all instances were turned into "Regular". It turned out that the default font contained `openTypeNamePreferred*` font info fields that made ufo2ft turn everything into the default font name-wise even though instance style names etc. were present.

The following fields should probably not be in the `default_font.info` when generating instances, unless they're being overridden by Designspace `InstanceDescriptor` attributes. This can confuse ufo2ft or just generate the wrong data in the instances. Print a warning.

- postscriptFontName
- styleMapFamilyName
- styleMapStyleName
- styleName

The following attributes can't be set directly and would have to be set in e.g. a `com.schriftgestaltung.customParameters` key:

- macintoshFONDName
- openTypeNameCompatibleFullName
- openTypeNamePreferred
- openTypeNamePreferredSubfamilyName
- openTypeNameUniqueID
- openTypeNameWWSFamilyName
- openTypeNameWWSSubfamilyName
- openTypeOS2Panose
- postscriptFullName
- postscriptUniqueID
- postscriptWeightName
- woffMetadataUniqueID
- (italicAngle? #577)

What about openTypeNameRecords in the default font? Sniff out the nameIDs of styleMapFamilyName, styleMapStyleName? What about styleName?

**Comment by belluzj** [comment]
About those:
* postscriptFontName
* styleMapFamilyName
* styleMapStyleName
* styleName

It sounds to me that those are specific to 1 single font anyway, so they should not be copied to instances in the first place?

**Comment by madig** [comment]
It turns out I overlooked that ufoProcessor actually copies font info attributes selectively: https://github.com/LettError/ufoProcessor/blob/1.07/Lib/ufoProcessor/__init__.py#L869-L918. I'll implement a skipping list and skip some more.
