### ISSUE TITLE
Non compatible glyphs export issue when masters are instances.

### ISSUE THREAD

**Issue by kosbarts** [googlefonts/fontmake#576]
Hello,

I am trying to export some static fonts from a glyphs file. There are 4 masters (300, 400, 500, 600) and 4 instances with the exact same values. Some outlines are not compatible but since there is no actual interpolation happening Glyphs exports the instances correctly. 

However, fontmake does not. I could export just the masters, in which case the outlines are correct, but when I export the instances all non-compatible glyphs are empty.

**Comment by madig** [comment]
Are you using fontmake v2.0.x?

**Comment by kosbarts** [comment]
I have updated and it says 1.10.1

**Comment by madig** [comment]
Too old, my new instance generator in 2.0.0 does what you want. Please update.

**Comment by kosbarts** [comment]
How do I upgrade to 2.0.0? I ran pip install -U fontmake and I still got 1.10.1

**Comment by madig** [comment]
Did you manage to get 2.0?

**Comment by kosbarts** [comment]
Yes, thanks. I was using Python 2.7 (default) and was only getting 1.0. All good. Thanks!
