### ISSUE TITLE
fixed mark position of interpolated instances

### ISSUE THREAD

**Issue by aminabedi68** [googlefonts/fontmake#585]
im not sure this is a mistake or an issue, when i extract interpolated instances as UFO, all mark positions are the same (=upper master). i work with fontforge and project is opensource.

variable font output:

![2019-09-15_13-39-22](https://user-images.githubusercontent.com/25493297/64919432-cbd57480-d7bf-11e9-9fd4-e12e9e38dbce.gif)

instance to UFO output:

![output_JnA0gf](https://user-images.githubusercontent.com/25493297/64919439-e9a2d980-d7bf-11e9-9b89-79399cfcfef4.gif)

**Comment by anthrotype** [comment]
If project is open source maybe you could share a link to the source files?

**Comment by aminabedi68** [comment]
of course
https://drive.google.com/open?id=1WQEBXG54aal7x-48tGqNzTrn3M6AklW_

**Comment by aminabedi68** [comment]
whole glyphs with duplicated anchor names are Arabic ligatures and named different inside fontforge, for example "uniFEF7":

![fontforge_2019-10-22_23-10-22](https://user-images.githubusercontent.com/25493297/67325696-6a24ca80-f522-11e9-9a77-56c9dd4d5eb5.png)

Source of fontforge file:
```
StartChar: uniFEF8
Encoding: 65272 65272 55
Width: 1372
Flags: HMW
AnchorPoint: "Anchor-4" 257 1822 baselig 1
AnchorPoint: "Anchor-4" 988 1356 baselig 0
AnchorPoint: "Anchor-2" 266 0 baselig 1
AnchorPoint: "Anchor-2" 976 0 baselig 0
LayerCount: 2
Fore
Refer: 25 1620 N 1 0 0 1 279 -87 2
Refer: 51 65276 N 1 0 0 1 0 0 2
PairPos2: "'kern' Horizontal Kerning in Arabic lookup 2 per glyph data 0" uni0639 dx=-180 dy=0 dh=-180 dv=0 dx=0 dy=0 dh=0 dv=0
PairPos2: "'kern' Horizontal Kerning in Arabic lookup 2 per glyph data 0" uni063A dx=-180 dy=0 dh=-180 dv=0 dx=0 dy=0 dh=0 dv=0
Ligature2: "'liga' Standard Ligatures in Arabic lookup 8 subtable" uniFEE0 uniFE84
LCarets2: 1 0
EndChar
```

and in features.fea file for anchor 4:
```
  pos ligature \uniFEF7 <anchor 867 1356> mark @Anchor4 
    ligComponent
      <anchor 257 1822> mark @Anchor4 ;
```

i don't know what happens to anchor 4 in generated UFO and i'm not sure this is a mistake or a bug, but as you see both names of anchor 4 are the same in features file. and consider that variable output works correctly. do I have to open an issue in fontforge github page?

**Comment by khaledhosny** [comment]
I don’t think FontForge is doing any anchor names gymnastics when exporting to UFO. I can’t check right now, but someone should verify and submit an issue to FontForge (together with some description about the naming scheme as UFO spec was silent about it last I checked).

**Comment by aminabedi68** [comment]
yes @anthrotype . UFOs generated with fontforge, i check the latest version and result is the same.
thank you @khaledhosny . I hope you can help me.

**Comment by khaledhosny** [comment]
Please report an issue against FontForge, nothing can be done here.

**Comment by aminabedi68** [comment]
i tried to delete ligature anchors and add them manually later ,fontmake has no warnings, but the problem still exist, i share the source files here to reproduce:
https://drive.google.com/open?id=1w-AonMFMC7pgfp6Zgi4uvoUkbSym8w3v

**Comment by anthrotype** [comment]
@aminabedi68 did you remove the anchors? Or you renamed them like I said above (appending _1, _2, etc.) suffix?

**Comment by anthrotype** [comment]
I see that the UFOs' features.fea files already contain mark and mkmk features. In that case, fontmake does not auto-generate them from the UFO anchors, but simply builds them as they are defined in features.fea.
If they are not working as expected the issue then is not in the mark feature writer but in your own feature code.

**Comment by aminabedi68** [comment]
OK, thank you @anthrotype, so the exported UFO format of fontforge isn't fully uncompressed.
