### ISSUE TITLE
vhea/vmtx table is not produced

### ISSUE THREAD

**Issue by RoelN** [googlefonts/fontmake#586]
I have this .glif:

```
<?xml version="1.0" encoding="UTF-8"?>
<glyph name="test" format="1">
  <advance width="1000" height="980" />
  <outline>
    ...
  </outline>
</glyph>
```

I would expect `vhea` and `vmtx` tables to be produced because a `height` is given, but only the `hhea` and `hmtx` tables are added.

Building the UFO through Glyphs.app does produce these tables.

I couldn't find a flag or setting to pass on to fontmake. How can I get `vhea` and `vmtx` to be produced?

**Comment by khaledhosny** [comment]
My guess it is ufo2ft issue. The code [here](https://github.com/googlefonts/ufo2ft/blob/5c8ce699f80c50bb38686844f869a712217634eb/Lib/ufo2ft/outlineCompiler.py#L98-L110) checks for some vertical metrics keys and does not build vertical tables unless all of them are present.

**Comment by anthrotype** [comment]
yes, just like Khaled said. @moyogo set it up like this: 
https://github.com/googlefonts/ufo2ft/commit/6d02ab62b07c549f057bbcaa36ea93c27eaf958a

So, the list of fontinfo attributes that ufo2ft expects in order to build vmtx/vhea is:

```
            "openTypeVheaVertTypoAscender",
            "openTypeVheaVertTypoDescender",
            "openTypeVheaVertTypoLineGap",
            "openTypeVheaCaretSlopeRise",
            "openTypeVheaCaretSlopeRun",
            "openTypeVheaCaretOffset",
```

**Comment by anthrotype** [comment]
glyphsLib has mappings between Glyphs.app's specific custom parameter names and UFO3 fontinfo attributes for `vheaVertTypoAscender`, `vheaVertTypoDescender`, `vheaVertTypoLineGap` (so setting the latter ones in your .glyphs file is equivalent to setting the respective UFO3 attributes):

https://github.com/googlefonts/glyphsLib/blob/bd378485d180d62976d3646e5c1d26fbda0bf330/Lib/glyphsLib/builder/custom_params.py#L325-L346

However it doesn't seem to have shorter name aliases for the last three of them: slope rise and run, and caret offset.

Can anybody check whether Glyphs.app does have custom parameters for those and what are they named?

/cc @belluzj @madig

**Comment by RoelN** [comment]
Thanks @khaledhosny and @anthrotype, adding the `openTypeVhea*` attributes builds the font with `vhea` and `vmtx` tables!

As far as I'm concerned we can close this issue, unless you want to continue the Glyphs.app discussion here, @anthrotype?

**Comment by madig** [comment]
In the files listed in https://github.com/googlefonts/glyphsLib/issues/253#issuecomment-343281616, I can find:

- openTypeHheaCaretOffset
- openTypeHheaCaretSlopeRise
- openTypeHheaCaretSlopeRun
- openTypeVheaCaretOffset
- openTypeVheaCaretSlopeRise
- openTypeVheaCaretSlopeRun

**Comment by anthrotype** [comment]
thanks for checking. so they are _not_ shortened, but they use the full name as the UFO3 attributes?

**Comment by madig** [comment]
Seems like it.

**Comment by anthrotype** [comment]
I haven't spent enough time thinking on this, but I have a feeling that _requiring_ to specify caret offset and slope for vertical typesetting seems a bit too much. I wonder if we could default to something sensible for these. I get the need for vhea vertical ascender/descender/linegap.. but caret?

**Comment by moyogo** [comment]
I agree, the vertical caret could fallback on something based on the italic angle.

**Comment by anthrotype** [comment]
> the vertical caret could fallback on something based on the italic angle.

Hm. Why should the post.italicAngle automatically determine the slope of the caret used for _vertical_ typesetting?
I think we should just default to an horizontal caret if the vhea caret(slope|offset) attributes are not explicitly defined.

BTW, even the vhea OT spec says

> For a vertical font, a horizontal caret is best.
