### ISSUE TITLE
Feature request: project.run_from_designspace() accepting a DesignSpaceDocument instance instead of a path

### ISSUE THREAD

**Issue by justvanrossum** [googlefonts/fontmake#588]
I find myself regularly generating `DesignSpaceDocument` instances programmatically, which I then would like feed to fontmake. I don't really have a need for these files on disk, and it feels a little cumbersome to first have to write it to disk as a physical `.designspace` file.

**Comment by madig** [comment]
Cosimo would interject to say that fontmake currently is not a library :smile: 

Is there a specific fontmake feature you need that `varLib.build()` and the `fontmake.instantiator` module do not provide?

**Comment by justvanrossum** [comment]
> Is there a specific fontmake feature you need that varLib.build() and the fontmake.instantiator module do not provide?

I seriously have no idea, but upon brief inspection it seems that fontmake does a lot more than invoke `varLib.build()`. I pretty much want to invoke fontmake without starting a subprocess. Calling `project.run_from_designspace()` does exactly what I need in one convenient call. The physical file needed for the designspace document is not a big hurdle, so if a feature request like this is out of scope, I won't further complain.

**Comment by justvanrossum** [comment]
Now, I see this line:
https://github.com/googlefonts/fontmake/blob/b12c53ba945ea851b13e69abfa2e7bdf2e62ee6a/Lib/fontmake/font_project.py#L208
...which makes it non-trivial to support path-less DesignSpaceDocument objects... So I'll just walk backwards into that hedge like Homer Simpson while I close this issue...

**Comment by madig** [comment]
fontmake is mostly glue for calling into ufo2ft. If you are generating variable fonts purely in-memory, I recommend looking at the public API to compile stuff from Designspaces. ufo2ft can work in-memory :)

**Comment by justvanrossum** [comment]
Thanks, that is a very useful example!
