### ISSUE TITLE
Building a variable font from designspace and interpolatable ttfs?

### ISSUE THREAD

**Issue by jenskutilek** [googlefonts/fontmake#590]
With `fontTools.varLib` I can build a variable font from a designspace file if the referenced UFOs are not present, but interpolatable TTFs with the same filename (except for the suffix) are in a folder called `master_ttf_interpolatable`.

Is the same thing possible with fontmake? Or any other way to take TTF masters as input?

**Comment by madig** [comment]
I think in that case you have to modify the Designspace to point to your TTFs. Maybe it's easier to write a small script?

**Comment by anthrotype** [comment]
you don't need fontmake for that. `fonttools varLib` can take a designspace file where the source filenames point to either interpolatable TTFs (or even .ttx files).

**Comment by anthrotype** [comment]
I mean `fonttools varLib` (alias for `python -m fontTools.varLib`) as in the command-line script, not `fontTools.varLib` the python module.

**Comment by jenskutilek** [comment]
Thanks. I was aware of the `fonttools varLib` method. I just thought somehow that fontmake would do the same, but it doesn't ;)
