### ISSUE TITLE
2 questions

### ISSUE THREAD

**Issue by aminabedi68** [googlefonts/fontmake#597]
hi, i have 2 questions:
1- is it possible to extrapolate across two masters with one axis?
2- this is my personal question,may be irrelevant, It's just a curiosity: glyphs without changes across masters, written once or twice in generated variable font? and is there a way (special settings or flag) to tell fontmake they are the same or maybe identified automatically?

**Comment by behdad** [comment]
1. Not currently.
2. Only once.

**Comment by aminabedi68** [comment]
thank you @behdad :)
