### ISSUE TITLE
Design Space to Variable Font conversion is not working.

### ISSUE THREAD

**Issue by rajputrajesh448** [googlefonts/fontmake#598]
Hi,

I am very new to this and I took the help of Adam from FontLab to understand the process of converting Design Space files into Variable Fonts from Fontmake.

I followed the process but still, the conversion is not happening and I am getting an error (Second Last Line) of which I don't have any idea. I would really appreciate it if you guys could help me out to correct this problem. Below is the code I got after running the Fontmake

Last login: Mon Nov 18 13:36:23 on ttys000
stock14068:~ rajeshkumar$ python3 -m fontmake -m /Users/rajeshkumar/Desktop/DesignSpace -o variable --output-path /Users/rajeshkumar/Desktop/VR
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/rajeshkumar/Library/Python/3.8/lib/python/site-packages/fontmake/__main__.py", line 451, in <module>
    sys.exit(main())
  File "/Users/rajeshkumar/Library/Python/3.8/lib/python/site-packages/fontmake/__main__.py", line 424, in main
    project.run_from_designspace(designspace_path, **args)
  File "/Users/rajeshkumar/Library/Python/3.8/lib/python/site-packages/fontmake/font_project.py", line 852, in run_from_designspace
    designspace = designspaceLib.DesignSpaceDocument.fromfile(designspace_path)
  File "/Users/rajeshkumar/Library/Python/3.8/lib/python/site-packages/fontTools/designspaceLib/__init__.py", line 1017, in fromfile
    self.read(path)
  File "/Users/rajeshkumar/Library/Python/3.8/lib/python/site-packages/fontTools/designspaceLib/__init__.py", line 1050, in read
    reader = self.readerClass(path, self)
  File "/Users/rajeshkumar/Library/Python/3.8/lib/python/site-packages/fontTools/designspaceLib/__init__.py", line 651, in __init__
    tree = ET.parse(self.path)
  File "src/lxml/etree.pyx", line 3467, in lxml.etree.parse
  File "src/lxml/parser.pxi", line 1839, in lxml.etree._parseDocument
  File "src/lxml/parser.pxi", line 1865, in lxml.etree._parseDocumentFromURL
  File "src/lxml/parser.pxi", line 1769, in lxml.etree._parseDocFromFile
  File "src/lxml/parser.pxi", line 1163, in lxml.etree._BaseParser._parseDocFromFile
  File "src/lxml/parser.pxi", line 601, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 711, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 640, in lxml.etree._raiseParseError
  File "/Users/rajeshkumar/Desktop/DesignSpace", line 1
lxml.etree.XMLSyntaxError: Document is empty, line 1, column 1
stock14068:~ rajeshkumar$ 

Best,
Rajesh

**Comment by rajputrajesh448** [comment]
Here is the link to Design Space Files – https://github.com/rajputrajesh448/Fonts/blob/master/DesignSpace.zip

**Comment by anthrotype** [comment]
Hi @rajputrajesh448 
I donloaded the zip file and run fontmake on the designspace file, this is the error message that I got (different from the one you copy-pasted above). 

```
$ fontmake -m "Emberly Variable Regular.designspace" -o variable
INFO:fontmake.font_project:Building variable font variable_ttf/Emberly Variable Regular-VF.ttf
Traceback (most recent call last):
[... omitting traceback info ...]
    "Can't find base (neutral) master in DesignSpace document"
ufo2ft.errors.InvalidDesignSpaceData: Can't find base (neutral) master in DesignSpace document
```

This is because you have two masters, a Thin and a Black, but the default values for wght and wdth axes is set to the location of the "Narrow" instance (400, 87.5).
In order for fontmake to be able to build a VF, you need to:

1) either change the default values for all the axes to match exactly the location of one of the existing masters (e.g. it should work if you set the default wght to, say, 100 (or 900) and the default wdth to 75 or 100).
2) or you have to add an extra master where you want your "neutral" master to be. You can interpolate the Narrow instance UFO with the two-master designspace, and then you re-insert this instance as a third master in between the Thin and Black.

You also have several glyphs that have incompatible outlines (different number of contours, or different number or type of segments in each contour) which make the cubic-to-quadratic conversion fail. I suppose these compatible masters are still in-development, but I justed wanted to point that out.

**Comment by anthrotype** [comment]
a "neutral" or default or base master is one such that its location is at the default coordinate along all of the axes.

**Comment by rajputrajesh448** [comment]
@anthrotype Thank you very much for your help, really appreciate it. I think I have a lot to cover on this.

**Comment by rajputrajesh448** [comment]
@anthrotype You mentioned that several glyphs have incompatible outlines. Is there any way I can find out exact glyphs that have these issues?

**Comment by anthrotype** [comment]
Yes, once you go past the first error about the neutral master, fontmake will tell you which glyphs are incompatible

**Comment by rajputrajesh448** [comment]
@anthrotype Thank you, just one more thing, you got a different error than me so I just wanted to confirm if I am using the correct command or not?

I am using this command (python3 -m fontmake -m PATH_TO_YOUR_DESIGNSPACE -o variable --output-path PATH_TO_DESIRED_VARIABLE_FONT), is it correct?

**Comment by anthrotype** [comment]
that command is correct

**Comment by anthrotype** [comment]
the `-m PATH_TO_DESIGNSPACE` is not the directory containing the document, but the path to the document itself

**Comment by rajputrajesh448** [comment]
@anthrotype Thank you very much for this help.

**Comment by rajputrajesh448** [comment]
@anthrotype Hi Cosimo, Thanks for your help earlier, I corrected all the issues in type and `python3 -m fontmake -m PATH_TO_YOUR_DESIGNSPACE -o variable --output-path PATH_TO_DESIRED_VARIABLE_FONT` in this code I guess the "PATH_TO_DESIRED_VARIABLE_FONT" is the path of the Variable Font. So what I am understanding is that I need to export a variable font first and then use it to compile everything.

And I did it, and this is what I got. But I am still not sure if I am doing it right or not.
Could you please have a look at and let me know if I am doing it right?

`Last login: Fri Nov 22 17:55:01 on ttys000
Rajeshs-MacBook-Pro:~ rajeshkumar$ python3 -m fontmake -m /Users/rajeshkumar/Desktop/DesignSpace/Emberly\ Variable\ Regular.designspace -o variable --output-path /Users/rajeshkumar/Desktop/DesignSpace/Emberly\ Variable\ Regular-VF.ttf
INFO:fontmake.font_project:Building variable font /Users/rajeshkumar/Desktop/DesignSpace/Emberly Variable Regular-VF.ttf
INFO:ufo2ft:Pre-processing glyphs
INFO:cu2qu.ufo:New spline lengths: 1: 1, 2: 973, 3: 1042, 4: 177, 5: 58, 6: 7
INFO:ufo2ft.filters:Running DecomposeComponentsFilter on Emberly-Thin
INFO:ufo2ft.filters:Running DecomposeComponentsFilter on Emberly-Black
INFO:ufo2ft.filters:Running DecomposeComponentsFilter on Emberly-ThinCondensed
INFO:ufo2ft.filters:Running DecomposeComponentsFilter on Emberly-BlackCondensed
INFO:ufo2ft:Building OpenType tables for Emberly-Thin
INFO:ufo2ft:Building OpenType tables for Emberly-Black
INFO:ufo2ft:Building OpenType tables for Emberly-ThinCondensed
INFO:ufo2ft:Building OpenType tables for Emberly-BlackCondensed
INFO:ufo2ft:Building variable TTF font
INFO:fontTools.varLib:Axes:
[{'default': 100.0,
  'hidden': False,
  'labelNames': {'en': 'Weight'},
  'map': [],
  'maximum': 1000.0,
  'minimum': 100.0,
  'name': 'weight',
  'tag': 'wght'},
 {'default': 75.0,
  'hidden': False,
  'labelNames': {'en': 'Width'},
  'map': [],
  'maximum': 100.0,
  'minimum': 75.0,
  'name': 'width',
  'tag': 'wdth'}]
INFO:fontTools.varLib:Internal master locations:
[{'weight': 100.0, 'width': 100.0},
 {'weight': 900.0, 'width': 100.0},
 {'weight': 100.0, 'width': 75.0},
 {'weight': 900.0, 'width': 75.0}]
INFO:fontTools.varLib:Internal axis supports:
{'weight': [100.0, 100.0, 1000.0], 'width': [75.0, 75.0, 100.0]}
INFO:fontTools.varLib:Normalized master locations:
[{'weight': 0.0, 'width': 1.0},
 {'weight': 0.8888888888888888, 'width': 1.0},
 {'weight': 0.0, 'width': 0.0},
 {'weight': 0.8888888888888888, 'width': 0.0}]
INFO:fontTools.varLib:Index of base master: 2
INFO:fontTools.varLib:Building variable font
INFO:fontTools.varLib:Loading master fonts
INFO:fontTools.varLib:Generating fvar
INFO:fontTools.varLib:Generating avar
INFO:fontTools.varLib:No need for avar
INFO:fontTools.varLib:Building variations tables
INFO:fontTools.varLib:Generating MVAR
INFO:fontTools.varLib:Generating HVAR
INFO:fontTools.varLib:Merging OpenType Layout tables
INFO:fontTools.varLib:Generating gvar
INFO:fontTools.varLib:Merging TT hinting
Rajeshs-MacBook-Pro:~ rajeshkumar$ `


Best
Rajesh

**Comment by anthrotype** [comment]
you should find a new variable font file in "/Users/rajeshkumar/Desktop/DesignSpace/Emberly\ Variable\ Regular-VF.ttf"

--output-path is where you would like to save your new VF. By default if you don't pass that option fontmake will save it to ./variable_ttf/NameOfYourFont-VF.ttf

**Comment by rajputrajesh448** [comment]
@anthrotype When giving it a path then I am getting this error 

`  File "/Users/rajeshkumar/Library/Python/3.8/lib/python/site-packages/fontTools/ttLib/ttFont.py", line 165, in save
    file = open(file, "wb")
IsADirectoryError: [Errno 21] Is a directory: '/Users/rajeshkumar/Desktop/DesignSpace'
Rajeshs-MacBook-Pro:~ rajeshkumar$ `

Last time instead of giving it a path of the folder I used the TTF location which I exported from FontLab. I understand that this is an export command but when I am choosing blank folder then it is giving me this error.

**Comment by m4rc1e** [comment]
You're passing in a dir. You need to pass it a filename e.g `/Users/rajeshkumar/Desktop/DesignSpace/font.ttf`

**Comment by anthrotype** [comment]
--ourput-path is the path to the file, not the directory.
There's an --output-dir option as well if your prefer.

**Comment by anthrotype** [comment]
For support questions you can also use the fontmake Gitter chat

**Comment by rajputrajesh448** [comment]
Sure Thanks!

**Comment by anthrotype** [comment]
Oh, apparently there isn't any fontmake Gitter chat... Sorry. Well, try the fonttools one.

**Comment by rajputrajesh448** [comment]
@anthrotype Got it, thank you I'll connect with you over there if I face any issue.
