### ISSUE TITLE
Kerning issue in VF

### ISSUE THREAD

**Issue by rajputrajesh448** [googlefonts/fontmake#602]
I've exported the VR through fontmake but the kerning looks off for the weight 100 (width 75-100). But when I am exporting the VR from Fontlab then the kerning works fine.

Here is the link to both the TTF and Design Space File
https://github.com/rajputrajesh448/Fonts

Best,
Rajesh

**Comment by anthrotype** [comment]
> I've exported the VR

VF as in variable font

> kerning looks off

Could you be a bit more specific?

**Comment by rajputrajesh448** [comment]
Oh my bad by VR I mean VF.

I exported the Variable Font through fontmake and when I am checking it on Axis-Praxis the Kerning for a few specific characters is not working (fo, fg, ij etc). As I am using FontLab so I exported a Variable Font directly from FontLab and then the kerning is working fine.

Here is the link to both the Variable TTF (Fontmake and FontLab)
https://github.com/rajputrajesh448/Fonts/blob/master/Emberly%20TTF.zip

And the link to the Design Space file
https://github.com/rajputrajesh448/Fonts/blob/master/EmberlyDesignSpace.zip

Thanks for your help.

**Comment by rajputrajesh448** [comment]
Okay! I removed the existing kerning from the characters I mentioned and then assigned fresh kerning classes and it worked fine. Hence I am closing this issue. 

But I would really appreciate it if you could share the code to extract the instances (Thin, Light, Extra Light, etc.) from the design space file.

Best,
Rajesh

**Comment by twardoch** [comment]
Rajesh,

when FontLab VI exports a VF, it performs the Match Kerning operation. When
it exports a DesignSpace, it does not, but you can do it yourself from the
Kerning panel local menu before you export DS+UFO. This will turn the
kerning in all masters into a compatible structure (same classes, matching
pairs etc.).

**Comment by rajputrajesh448** [comment]
@twardoch Thanks Adam! That worked fine. 

Do you have any idea how can I export instances (Thin, Light, etc) through font make for different formats (ttf, otf,  woff, etc)?

**Comment by anthrotype** [comment]
Use the --interpolate or -i option to generate instances

**Comment by rajputrajesh448** [comment]
Thank you, Cosimo! 
But the output which I am getting is .UFO where do I mention in this code that the output should be TTF, OTF or WOFF.

`python3 -m fontmake -m /Users/rajeshkumar/Desktop/DesignSpace/Emberly\ Variable\ Regular.designspace --interpolate --output-path /Users/rajeshkumar/Desktop/DesignSpace/Emberly\ Variable\ Regular.ttf`

I am also getting this error
`  raise ValueError("output_path requires a single input")
ValueError: output_path requires a single input`

I don't have any prior experience in coding and really appreciate your help.

Best,
Rajesh

**Comment by madig** [comment]
Use `-o variable`, otherwise you are trying to make static TTFs.

**Comment by anthrotype** [comment]
He wants to interpolate static instances.
When the output files are more than one as in this case you need to use --output-dir with the path to the directory where you want to save the output instances. Or simply don't pass any --ourput-path nor --ourput-dir option and let fontmake save the files in the default folders that it creates.

**Comment by anthrotype** [comment]
Please try to make sense of the fontmake --help, and if something doesn't make sense for you you then ask for clarification.
