### ISSUE TITLE
Instantiation from Glyphs source: usWeightClass is set wrong

### ISSUE THREAD

**Issue by yanone** [googlefonts/fontmake#615]
When creating static instances from a Glyphs source, the instance’s interpolation space weight value is used for `usWeightClass` as opposed to the appropriate weight class value.

I had actually added a `weightClass` custom parameter to each instance using the simple script below, so the custom parameter should be used for `usWeightClass` when present, or otherwise calculated in `fontmake` on the fly as below:

```python
from GlyphsApp import *
f = Glyphs.font

weights = {
'Thin': 100,
'ExtraLight': 200,
'UltraLight': 100,
'Light': 300,
'Normal': 400,
'Regular': 400,
'Medium': 500,
'DemiBold': 600,
'SemiBold': 600,
'Bold': 700,
'UltraBold': 800,
'ExtraBold': 800,
'Black': 900,
'Heavy': 100,
}

for i in f.instances:
	i.customParameters['weightClass'] = weights[i.weight]
```

**Comment by yanone** [comment]
The same thing goes for VF instances. It's the same source, the instances have a `weightClass` custom parameter.

```
 >> com.google.fonts/check/varfont_instance_coordinates
    Check variable font instances have correct coordinate values
    with ./Fonts/vf/Petrona[wgth].ttf

    * FAIL: Instance "Thin" wght value is "32.0". It should be "100.0" [code: bad-coordinate]
    * FAIL: Instance "ExtraLight" wght value is "40.0". It should be "200.0" [code: bad-coordinate]
    * FAIL: Instance "Light" wght value is "49.0". It should be "300.0" [code: bad-coordinate]
    * FAIL: Instance "Regular" wght value is "61.0". It should be "400.0" [code: bad-coordinate]
    * FAIL: Instance "Medium" wght value is "76.0". It should be "500.0" [code: bad-coordinate]
    * FAIL: Instance "SemiBold" wght value is "94.0". It should be "600.0" [code: bad-coordinate]
    * FAIL: Instance "Bold" wght value is "117.0". It should be "700.0" [code: bad-coordinate]
    * FAIL: Instance "ExtraBold" wght value is "145.0". It should be "800.0" [code: bad-coordinate]
    * FAIL: Instance "Black" wght value is "180.0". It should be "900.0" [code: bad-coordinate]

    Result: FAIL
```

**Comment by arrowtype** [comment]
Small nitpick in your script: 

I think probably `'Heavy': 100,` be `1000`, correct?

**Comment by yanone** [comment]
Oh, you're right. But I took the values from Glyphs UI, and there it says 900, not 1000. But 100 is wrong anyway. Thanks.

**Comment by anthrotype** [comment]
That's unexpected. It could be something in glyphsLib.
Have you got source files to share so we can take a look?
thanks

**Comment by yanone** [comment]
Of course, sorry: https://github.com/yanone/Petrona/blob/master/Sources/Petrona-ROMAN-MASTER-NEW-W.glyphs

**Comment by anthrotype** [comment]
how did you build the VF exactly?
`fontmake -g MyFont.glyphs -o variable` or something fancier?

**Comment by yanone** [comment]
Just like that

**Comment by anthrotype** [comment]
oh I see. You have "Axis Location" custom parameters for the masters, but the values are in internal design coordinates. They are meant to define the _user-space_ coordinates of the masters.

**Comment by yanone** [comment]
And *user-space coordinates* are `usWeightClass` values?
Thing is, the font doesn't compile without `Axis Location` parameters: `ufo2ft.errors.InvalidDesignSpaceData: Can't find base (neutral) master in DesignSpace document`

**Comment by anthrotype** [comment]
yea.. Because none of your instances locations correspond to one of the masters, and when Axis Location params are missing, glyphsLib will infer the master's user-space location from the corresponding instances.
We really need to add support for the new `Axis Mapping` custom parameter... /cc @madig @belluzj

**Comment by m4rc1e** [comment]
Yanone, I'm attaching a .glyphs file which will build.

I did the following:

- Turn Medium instance into a master
- Delete Regular instance since no instances can match it (as Cosimo pointed out)
- Delete bracket layers in Peso.

You will need to readd the bracket layers in the peso and add them for each later. I deleted them so I could just get a working build.


[Petrona-ROMAN-MASTER-NEW-W_mf_tweak.glyphs.zip](https://github.com/googlefonts/fontmake/files/3955823/Petrona-ROMAN-MASTER-NEW-W_mf_tweak.glyphs.zip)

**Comment by anthrotype** [comment]
currently glyphsLib has two alternative ways to define the Designspace axes mappings (that will go into avar).

1) via Axis Location custom parameters which are set on the masters only
2) by inferring the master's user-space locations from the instances that have the same internal design location as a master

The problem with 1) is that it only allows to set user->internal mappings for the masters, but not for anything in between.
The problem with 2) is that it is implicit and thus obscure, and also one needs to have at least as many instances as there are masters

We need to support a new method introduced recently called "Axis Mapping" that allows more flexibility in defining these mappings.
need to find the time to understand how it works.
If you'd like to research a bit and let us know how it is supposed to work, it'd greatly help.

**Comment by anthrotype** [comment]
for background see https://github.com/googlefonts/glyphsLib/issues/568 and https://github.com/googlefonts/glyphsLib/issues/483

**Comment by yanone** [comment]
So for understanding, I set the `Axis Location` parameter to the `weightClass` of their respective instances. The problem you described in 1) is this?:

```
 >> com.google.fonts/check/varfont_instance_coordinates
    Check variable font instances have correct coordinate values
    with ./Fonts/vf/Petrona[wght].ttf

    * FAIL: Instance "ExtraLight" wght value is "148.0". It should be "200.0" [code: bad-coordinate]
    * FAIL: Instance "Light" wght value is "202.0". It should be "300.0" [code: bad-coordinate]
    * FAIL: Instance "Regular" wght value is "274.0". It should be "400.0" [code: bad-coordinate]
    * FAIL: Instance "Medium" wght value is "364.0". It should be "500.0" [code: bad-coordinate]
    * FAIL: Instance "SemiBold" wght value is "461.2244873046875". It should be "600.0" [code: bad-coordinate]
    * FAIL: Instance "Bold" wght value is "578.5714263916016". It should be "700.0" [code: bad-coordinate]
    * FAIL: Instance "ExtraBold" wght value is "721.4285736083984". It should be "800.0" [code: bad-coordinate]
```

**Comment by anthrotype** [comment]
Correct!

**Comment by yanone** [comment]
Okay, great. Thanks everyone for the quick responses. I'm closing this one here.
