### ISSUE TITLE
Duplicate glyph error from unnecessary layer

### ISSUE THREAD

**Issue by yanone** [googlefonts/fontmake#616]
Generating a Glyphs source such as [this one](https://github.com/googlefonts/OswaldFont/blob/master/sources/Oswald.glyphs) leads to a `KeyError: "glyph 'Dje-cy' already exists"` error. 
The glyph in question (and others) carry design layers not necessary to interpolation, and are somehow exported into separate glyphs using the same glyph name, then reported as duplicates.

Deleting all those layers in the source fixes the problem, but they should be allowed to stay and instead filtered by `fontmake`.

<img width="257" alt="Bildschirmfoto 2019-12-12 um 13 53 07" src="https://user-images.githubusercontent.com/175386/70715525-c3bba100-1cea-11ea-8120-8edcc2f60eca.png">

**Comment by madig** [comment]
Haven't checked the source, but do any of those layers have the same exact name?

**Comment by yanone** [comment]
Yes, two are indeed identical (the time string).

**Comment by madig** [comment]
This will currently trip up glyphsLib. https://github.com/googlefonts/glyphsLib/issues/566

**Comment by yanone** [comment]
I see. It is indeed the same issue. Will close this. Thank you.
