### ISSUE TITLE
fontmake dies with "unexpected keyword argument 'locked'"

### ISSUE THREAD

**Issue by psb1558** [googlefonts/fontmake#618]
Here's the error message:

```
  File "/Users/peterbaker/work/p3/lib/python3.7/site-packages/ufoLib2/objects/info.py", line 77, in _convert_optional_list
    result.append(klass(**d))
TypeError: __init__() got an unexpected keyword argument 'locked'
```

Using fontmake -m with UFOs exported from Glyphs, where one or more of the fontinfo.plist files has something like this:

```
        <key>guidelines</key>
        <array>
                <dict>
                        <key>angle</key>
                        <integer>0</integer>
                        <key>locked</key>
                        <true/>
                        <key>x</key>
                        <integer>-271</integer>
                        <key>y</key>
                        <integer>17</integer>
                </dict>
        </array>
```

Locate and unlock any global guides and export as UFO again, and the error goes away.

**Comment by anthrotype** [comment]
There is no "locked" attribuite in UFO Guidelines as far as I am aware, see
http://unifiedfontobject.org/versions/ufo3/fontinfo.plist/

You said you have exported this UFO from Glyphs.app? Maybe try ask on their forum.
They should store this extra private app-specific data somewhere else, e.g. in the lib.plist
/cc @schriftgestalt

**Comment by anthrotype** [comment]
We can also consider updating the UFO spec to support this new attribute, but one needs to make a proposal. I haven't seen one.

**Comment by psb1558** [comment]
I'll mention this in the Glyphs forum.

**Comment by schriftgestalt** [comment]
I fixed this already. Need to upload an update
