### ISSUE TITLE
Static fonts are different to variable fonts

### ISSUE THREAD

**Issue by weiweihuanghuang** [googlefonts/fontmake#622]
I have a 9 master set up with 4 corner masters and 5 intermediates masters as such:

![a](https://user-images.githubusercontent.com/1271897/71982818-8874a980-3279-11ea-8023-8f4e9bb69d0f.png)

In the variable font generated with fontmake: the letters look like this:
![var](https://user-images.githubusercontent.com/1271897/71983013-f6b96c00-3279-11ea-9495-550f6e061f33.png)

In the static font, the E is distorted and incorrect:
![static](https://user-images.githubusercontent.com/1271897/71983000-f28d4e80-3279-11ea-9b9f-943875f1e089.png)

Is this to do with the interpolation algorithm being used, i.e. varLib vs MutatorMath, and the fact that there is an intermediate master that does not connect in a horizontal or vertical line to another master? How do I make sure the results will be the same?

Here is the problem distilled to 2 letters and 2 intermediates:
![b](https://user-images.githubusercontent.com/1271897/71982866-a17d5a80-3279-11ea-8adf-7f52edf1d5df.png)

[DesignspaceProblem.zip](https://github.com/googlefonts/fontmake/files/4035516/DesignspaceProblem.zip)

**Comment by weiweihuanghuang** [comment]
So one way to fix this issue seems to be to just make sure the intermediate masters contain the same glyphs – even if they do not need an adjusted intermediate master...

**Comment by madig** [comment]
Which fontmake version are you using?

**Comment by weiweihuanghuang** [comment]
Ahh, oops I was running the wrong fontmake... wasn't running the correct one inside my env for some reason.
