### ISSUE TITLE
fontmake doesn't read styleMapFamilyName and styleMapStyleName?

### ISSUE THREAD

**Issue by weiweihuanghuang** [googlefonts/fontmake#624]
If nothing is wrong with my designspace file, then it seems not? Why not?

**Comment by madig** [comment]
What are you trying to generate? Instances? VFs?

fontmake version?

**Comment by weiweihuanghuang** [comment]
Generate instances, and i am using 2.0.8

**Comment by madig** [comment]
Can you post the Designspace somewhere? What do you expect to happen?

fontmake will write the UFOs to disk, inspect what gets put in there.

**Comment by weiweihuanghuang** [comment]
I expected the styleMapStyleName and styleMapFamilyName to be written into the instances.

The .designspace document: https://gist.github.com/weiweihuanghuang/07d80fac143e080d241ca258f56e83bd

**Comment by madig** [comment]
It's `stylemapfamilyname`, not `styleMapFamilyName`: https://github.com/fonttools/fonttools/tree/master/Doc/source/designspaceLib#attributes-9

**Comment by weiweihuanghuang** [comment]
Thank you!
