### ISSUE TITLE
Feature request: build strikeout & underline values into the MVAR table.

### ISSUE THREAD

**Issue by arrowtype** [googlefonts/fontmake#626]
I am trying to set specific underline & strikeout values in Recursive, and finding that they don't make it into the `MVAR` table, as I believe they should. [The `MVAR` spec includes strikeout and underline values](https://docs.microsoft.com/en-us/typography/opentype/otspec182/mvar), and if a font contains a large weight range, it would be very useful to be able to specify these values in a way that works harmoniously with stroke thickness.

## Current state

I see that my custom underline values are going into the `post` table:

```
<underlinePosition value="-145"/>
<underlineThickness value="150"/>
```

Also, FontMake is placing my custom strikeout values in the `OS/2` table:

```
<yStrikeoutSize value="80"/>
<yStrikeoutPosition value="314"/>
```

However, neither values seem to be making it into the MVAR table, which leads to poor results where these values are (partially) rendered, such as macOS Pages. In the following image, the underline value should visually match stem thickness. Instead, the value is only present in the `post` table and is taken from my heaviest sources, so it is much too thick for light weights.

![image](https://user-images.githubusercontent.com/45946693/72392419-10393880-36fe-11ea-9a0e-21c7ce0ee798.png)

More discussion and background at https://github.com/arrowtype/recursive/issues/285

**Comment by anthrotype** [comment]
strange, this should be supported. When varLib is fed masters with different strikeout or underline position values, it should use them to build the MVAR.

Can you provide a designspace file and the master TTFs so that I can try reproduce?

**Comment by arrowtype** [comment]
Following up on this: I’ve just been able to build variable fonts successfully with custom values here. See the linked issue for more details, if you want. 

Thanks!
