### ISSUE TITLE
Variation Font Origin custom parameter is now named Variable Font Origin

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/fontmake#636]
fontmake v2.0.9
Python 3.7.6
macOS 10.15.1

I have a two axis (wght/opsz), 4 master, 6 instance *.glyphs source based build with the following master definitions:

| Master  | opsz | wght | Variable Font Origin? |
|     :---:      |     :---:      |     :---:      |     :---:      | 
| 1  | 11  | 380 | Y |
| 2 | 11 | 734 | N  |
| 3 | 18 | 380 | N |
| 4 | 18 | 734  | N |

We need to define the default opsz value as 11 in the fvar table of the *.ttf variable font build artifacts compiled with fontmake. 

```
$ fontmake -g [source path] -o variable --output-dir [output dir path] --master-dir [master dir path] --instance-dir [instance path]
```

Glyphs appears to support a "Variable Font Origin" custom parameter that allows you to set one master as the "Origin".  The master that we've set is shown in the table above.  With that approach, our build has a fvar table opsz axis default of 18.  This is the value that shows up in the designspace file as well.

I take the "Origin" name to indicate "default"; however, this is not clear and perhaps I am using this incorrectly.   In any case, I cannot find a way to define the default opsz value in sources and we are currently working around this issue with a post-compile script.  Is it possible to define the opsz axis default with *.glyphs source based fontmake compiles?

**Comment by anthrotype** [comment]
glyphsLib has it as "_Variation_ Font Origin":
https://github.com/googlefonts/glyphsLib/blob/af5ab0b380ba9fc2100a0b91223d41a9c6bb0400/Lib/glyphsLib/builder/axes.py#L523

@schriftgestalt was it renamed at some point to "_Variable_ Font Origin"?

If so I guess we need to support both names, for backward compat

PRs welcome

**Comment by chrissimpkins** [comment]
Thanks Cosimo!  I had a look through glyphsLib and couldn't track this down.

> PRs welcome

Sure, I'd be happy to submit one.  I'll have a look at it this evening.

**Comment by chrissimpkins** [comment]
https://github.com/googlefonts/glyphsLib/pull/587
