### ISSUE TITLE
question: nonlinear interpolation

### ISSUE THREAD

**Issue by aminabedi68** [googlefonts/fontmake#642]
hi
i have a question: is there any solution to have a nonlinear interpolation between 2 masters? (like ease (-/in/out)) and turn it on/off for desired characters? i have no idea but i think it can be a good way to reduce number of masters in complicated multi-axis projects.

**Comment by madig** [comment]
Not possible in the current OpenType specification. Look around for "Higher Order Interpolation" (or "HOI"), you'll find some people trying to emulate it.
