### ISSUE TITLE
Axis assumption causes fail with single master & instance glyph file

### ISSUE THREAD

**Issue by kontur** [googlefonts/fontmake#644]
Attached a .glyphs file with a single master and a single instance: https://www.dropbox.com/s/qqug3jq591uvnd9/TestFont.glyphs?dl=0

When running `fontmake -g TestFont.glyphs -o ufo` (`-o otf` is the same error) execution fails with error:

```
File ".../fontTools/designspaceLib/__init__.py", line 890, in readLocationElement
    raise DesignSpaceDocumentError("No axes defined")
fontTools.designspaceLib.DesignSpaceDocumentError: No axes defined
```

`glyphslib` seems to be extracting the font fine, e.g. `glyphs2ufo TestFont.glyphs` gives me an UFO and designspace that look like what I'd expect - the designspace has no axes definitions, of course, because it's a single master file.

The thrown error seems to not be `fontTools`'s fault, because it shouldn't be needing to involve `designLib` in the first place. And naturally the missing axes, when instructing to work off that designspace, will fail. If I use `glyphslib` to extract the ufo/designspace and then calling `fontmake -u TestFont.ufo -o otf` the compilation works, but `fontmake -m TestFont.designspace` will give the same error. 

So is there a need to check more closely what `-g` gets from `glyphslib` before choosing the compilation path?

My installed package versions are `fontmake 2.0.10` `fonttools 4.5.0` `glyphsLib 5.1.6` `ufo2tf 2.12.2`.

**Comment by anthrotype** [comment]
Thanks. Yes, I can reproduce.
GlyphsLib should still output a single wght axis (weight is the default implicit axis when no `Axes` custom parameter are defined), instead for some reasons it is writing no axes at all in the generated designspace. A designspace without any axes definitions is invalid.

Can you try to add an `Axes` custom parameter with a single Weight axis? It should work around that issue.

cc @madig

**Comment by anthrotype** [comment]
I think the issue is in this line:

https://github.com/googlefonts/glyphsLib/blob/ce68b1a5d7260527278ab84c91e067dff268301d/Lib/glyphsLib/builder/axes.py#L218

in your font, the only master has location Weight=400, which is equal to the default location for Weight; the result of the if statement above makes it skip altogether.

It is a limit case but we should be able to support this. I'll send a PR to glyphsLib soon.

**Comment by madig** [comment]
I tried to work around exactly that but got stuck, because the entire glyphs2ufo logic needs to be overhauled. Use the Axes parameter in the meantime.

**Comment by anthrotype** [comment]
https://github.com/googlefonts/glyphsLib/releases/tag/v5.1.9

**Comment by kontur** [comment]
Thanks for the quick action on this 👍
