### ISSUE TITLE
woff files?

### ISSUE THREAD

**Issue by EwonRael** [googlefonts/fontmake#646]
Hey,

Is there currently support for, or planned support for outputting woff files?

**Comment by m4rc1e** [comment]
You can use Bramstein's webfonttools, https://github.com/bramstein/homebrew-webfonttools to do this.

**Comment by anthrotype** [comment]
Fonttools ttx can also compile woff and woff2 (with the --flavor option).
I don't know if fontmake should also do that. It could, but I don't see a real need.

**Comment by EwonRael** [comment]
No need! As long as there's a way to do this with scripting I'm happy. Thanks for pointing me in the right direction.
