### ISSUE TITLE
Designspace to ufo does nothing?

### ISSUE THREAD

**Issue by EwonRael** [googlefonts/fontmake#650]
Hi it's me again...

Right now if I try to output ufo files from a designspace files nothing happens

`fontmake -o ufo -m file.designspace`

throws no errors up, but also doesn't output anything?

for reference both

`fontmake -o ufo -g file.glyphs` and `fontmake -o ttf -m file.designspace`

seem to run as expected, outputting files

**Comment by anthrotype** [comment]
What do you want to do? If you want to make instance UFOs then you need to use -i option. Without -i the default is to output the masters only. But with a designspace input the masters are already UFOs, there is nothing to do if you request.
 -o ufo

Fontmake could probably print some message like "nothing to do" or similar to make it clear it isn't doing anything.

**Comment by EwonRael** [comment]
hmmm. I'm still having issues with this.

Let's say I download [AdobeVFPrototype](https://github.com/adobe-fonts/adobe-variable-font-prototype) and I run the following command:

`fontmake -o ttf -i "Black Medium Contrast" -m AdobeVFPrototype.designspace`

it spits out a ttf file as expected. When I run this command:

`fontmake -o ufo -i "Black Medium Contrast" -m AdobeVFPrototype.designspace`

It doesn't seem to output anything? Am I still formatting something wrong?

Thanks!

**Comment by anthrotype** [comment]
It should. Look at instance_ufo directory

**Comment by EwonRael** [comment]
https://youtu.be/IsyAaN-iNF4

**Comment by punchcutter** [comment]
The instances should be generated by default relative to the designspace file. So there should be an `instances` folder generated inside of `/home/owen/Downloads/adobe-variable-font-prototype-master/RomanMasters`

**Comment by EwonRael** [comment]
this was the answer thank you

**Comment by anthrotype** [comment]
Thanks Zachary. Yes, the designspace file itself specifies the filenames of the instance UFOs, fontmake uses that to save the generated instances.
