### ISSUE TITLE
Append dict info in ufo instance from designspace file?

### ISSUE THREAD

**Issue by EwonRael** [googlefonts/fontmake#653]
Hi I'm back, thanks for your continued help.

When I build a ufo instance from a designspace file, fontmake doesn't appear to append any dict info as specified in the instance.

I'm looking at what's outlined in [this document here](https://github.com/fonttools/fonttools/tree/master/Doc/source/designspaceLib#31-lib-element). It looks like I should be able to include a "lib" element and put all of my favourite instance specific metadata in there, but as far as I can tell fontmake just ignores all of that.

Is this just the usual case of me missing something?

Thank you

**Comment by madig** [comment]
Designspace lib elements are for tools that read the Designspace. They are not written to instances.

**Comment by anthrotype** [comment]
Like Nikolaus said, the designspace instance lib element is for private, authoring-tool specific data. In glyphsLib we use that to store some instance data that is only in the .glyphs source, and then fontmake applies it to the generated instances. 

> put all of my favourite instance specific metadata in there

what kind of metadata are you trying to set?

**Comment by EwonRael** [comment]
Boo!

I want to include stuff like the openTypeNamePreferredFamilyName or the postscriptFullName. 

Is there another way to do this? Worst case scenario I can sed into the fontinfo.plist, but I'm looking for a more elegant solution when it comes to building scripts to help with workflow.

Let me know, and thanks again for all of this help.

**Comment by madig** [comment]
postscriptFullName is set by an instance attribute iirc

you can piggy-back on glyphsLib:

```
  <instances>
    <!-- [...] -->
    <instance stylename="Regular">
      <location>
        <dimension name="Weight" xvalue="400"/>
      </location>
      <lib>
        <dict>
          <!-- Cut here -->
          <key>com.schriftgestaltung.customParameters</key>
          <array>
            <array>
              <string>panose</string>
              <array>
                <integer>1</integer>
                <integer>2</integer>
                <integer>3</integer>
                <integer>4</integer>
                <integer>5</integer>
                <integer>6</integer>
                <integer>7</integer>
                <integer>8</integer>
                <integer>9</integer>
                <integer>10</integer>
              </array>
            </array>
          </array>
          <!-- Cut here -->
        </dict>
      </lib>
    </instance>
    <!-- [...] -->
  </instances>
```

every font info attribute is a an array of name and value.

**Comment by anthrotype** [comment]
instance names you can set them with designspace `<instance>` element's attributes, see the full list at https://fonttools.readthedocs.io/en/latest/designspaceLib/readme.html#instance-element

You can file an issue in fonttools repository if you like to request additional instance-related data to be added to the DesignSpace specification.

**Comment by EwonRael** [comment]
hmm. @anthrotype I will look into requesting more instance-related data in the designspace specs, although, there's so many metadata fields that it feels like having a way to add arbitrary ones might be nice, especially if we come up with new metadata fields in the future we don't have to adjust the workflow... I will bring it up in fonttools repository. I'm aware of the existing attributes, still doesn't give me a way to set the openTypeNamePreferredFamilyName.

@madig I don't know what you mean quite by the glyphsLib piggyback? Is there a way to embed text info into glyphsLib and just type out:
`<key>openTypeNamePreferredFamilyName</key>`
`<string>Bodoni* 06</string>`
or something to that effect?

I will look at what you have written up but maybe you could clarify a bit for my not very tech savvy brain?

Thank you both very cool.

**Comment by madig** [comment]
make the instance lib look like this:

```xml
      <lib>
        <dict>
          <!-- Cut here -->
          <key>com.schriftgestaltung.customParameters</key>
          <array>
            <array>
              <string>openTypeNamePreferredFamilyName</string>
              <string>Bodoni* 06</string>
            </array>
          </array>
          <!-- Cut here -->
        </dict>
      </lib>
```

maybe that works

**Comment by EwonRael** [comment]
Holy cow that did the trick! I am forever indebted to you @madig
