### ISSUE TITLE
Is it possible to create conditional variation VF without rules?

### ISSUE THREAD

**Issue by aminabedi68** [googlefonts/fontmake#655]
hi
I have a problem and I can't find a good short solution for that:
I have an Arabic font with two different dot styles and want to create a variable font to switch with an axis but i don't want to allow users to choose any points between, I know what is the normal way: conditional rules, but I realize if I replace dots in VF axis variation they don't change in all glyphs with their references. so it seems I have to replace whole glyphs with dots and add many alternate glyphs with all possible kernings... if I could find a way to change the smooth variation (between two fonts with different dots) to conditional variation without rules... so is it possible? or any better solution? please help. thank you.

**Comment by aminabedi68** [comment]
i was talking to my friend who working with Glyphs and created the same VF feature before, he told me he just changed dots and all referenced dots changes with conditional rules too, so i'm pretty sure there is a way to implement that on fontmake, going to open an issue.

**Comment by twardoch** [comment]
Don’t use composite glyphs. Decompose all encoded Arabic letters into strokes and dots, then position the dots with GPOS.

You can do the swapping with an ssXX feature. Is there a reason why you prefer to use an axis?

**Comment by aminabedi68** [comment]
I think i can understand your solution now, it's very cool! i have not seen this before, so let me check what should we done in a case:
for example we are going to type letter sheen (U+0634), we need to add a line into GSUB isolated form: [sheen(input)] to [sheen(our glyph without dots)] + [treedotsabove]
i'm not sure about the output, is it working? and also a kerning line in GPOS kerning pair for sheen and treedotsabove to move dots x and y position to the correct place above the sheen glyph. please correct me if i have made a mistake or forgot sth, and No, there is no reason to use an axis if I can solve it with with ssxx, thank you. this is very brilliant idea! 👌
