### ISSUE TITLE
Bracket layer not generating

### ISSUE THREAD

**Issue by weiweihuanghuang** [googlefonts/fontmake#657]
[Archive.zip](https://github.com/googlefonts/fontmake/files/4556616/Archive.zip)

Please see the two files here, the have the following master structure
Both of these generate in Glyphs app, but not in fontmake 2.1.0

Test.glyphs:
<img width="95" alt="Screen Shot 2020-04-30 at 4 59 01 pm" src="https://user-images.githubusercontent.com/1271897/80681375-eddbf700-8b03-11ea-9980-1bd711fd426b.png">

I get this error:
```
fontmake: Error: In 'Test.glyphs' -> 'master_ufo/ProdigySans.designspace' -> 'master_ufo/ProdigySans.designspace': Interpolating instance 'ExtraLight' failed.: Failed to generate instance of glyph 'dollar.BRACKET.149': list index out of range. (Note: the most common cause for an error here is that the glyph outlines are not point-for-point compatible or have the same starting point or are in the same order in all masters.)
```

Test-2.glyphs
<img width="93" alt="Screen Shot 2020-04-30 at 4 59 05 pm" src="https://user-images.githubusercontent.com/1271897/80681372-ec123380-8b03-11ea-98c5-07cc20b7affc.png">
This means 

Erorr message:
```
fontmake: Error: In 'Test-2.glyphs' -> 'master_ufo/ProdigySans.designspace' -> 'master_ufo/ProdigySans.designspace': Interpolating instance 'ExtraLight' failed.: Failed to generate instance of glyph 'dollar.REV_BRACKET.149': list index out of range. (Note: the most common cause for an error here is that the glyph outlines are not point-for-point compatible or have the same starting point or are in the same order in all masters.)
```

It seems to expect every layer to be interpolable?

**Comment by anthrotype** [comment]
All the bracket layers with the same name (in your case [149]) must be interpolatable with each other, yes. They will go on to make up their own separate glyph in the variable font

**Comment by weiweihuanghuang** [comment]
I see, so they need to exist regardless of whether they are going to be swapped in the end font or not?

**Comment by madig** [comment]
A swappable glyph must follow the same rules as any other, and the rule says that everything needs to be compatible for VFs and interpolation. Swappable glyphs are their own glyphs, because there are no layers in OpenType.
