### ISSUE TITLE
Option for external feature file?

### ISSUE THREAD

**Issue by simoncozens** [googlefonts/fontmake#660]
I'm trying to build a font which a Glyphs source for the outlines/metrics/info but an external .fea file for layout. I could obviously do it in two steps (fontmake to create OTF, then feaLib to add features) but I'm surprised there isn't an obvious way to do this from fontmake. Confusingly the options say:

```
  --mti-source MTI_SOURCE
                        Path to mtiLib .txt feature definitions (use instead
                        of FEA)
```

But there is no other reference to FEA.

**Comment by madig** [comment]
There's no obvious way because both UFO and Glyphs formats package feature files inside, so this is an unsupported edge case. The MTI switch is just bolted on because some Noto fonts have MTI source feature files.

**Comment by anthrotype** [comment]
you could try using an `include` statement that references the external feature file. That's supposed to work

**Comment by twardoch** [comment]
Include works in many cases :)

**Comment by simoncozens** [comment]
OK, thanks - got it working with a reference in the Glyphs file and `--master-dir .` to make references resolve.
