### ISSUE TITLE
Postscript name Instance custom parameter from a Glyphs file - is it OK?

### ISSUE THREAD

**Issue by EbenSorkin** [googlefonts/fontmake#665]
Does fontmake accept/use an instance custom parameter for Postscript name from a Glyphs file?

Related - what custom parameters for the file/master/instance are either desirable/undesirable to have when exporting to VF from fontmake? Does anyone have a current definitive list or a start on one?

**Comment by madig** [comment]
1. I can't remember, but there is a `postscriptfontname` attribute, see https://fonttools.readthedocs.io/en/latest/designspaceLib/readme.html#id16. Maybe glyphsLib translates accordingly.
2. (Un)desirable in what way? None of them are required I think.

**Comment by anthrotype** [comment]
Try setting `postscriptFontName` custom parameter in the Glyphs instances, does that work?

**Comment by EbenSorkin** [comment]
I'll try it and see.

**Comment by EbenSorkin** [comment]
It didn't seem to make a difference. So far no custom parameters for instances I have tried seem to have an impact on the font that's made so I got rid of all of mine. I would like to be able to use them at some point later because I'd like finer control and to make the result not require manually using TTX, OTM etc.
