### ISSUE TITLE
question/feature request: calculate masters in other corners to reduce inputs

### ISSUE THREAD

**Issue by aminabedi68** [googlefonts/fontmake#677]
Hi
it would be great if fontmake has an option to calculate masters in other corners to reduce input files(it's possible i guess), it would be a big help, especially on multi-axis variable fonts. for example, I have a variable font with 5 axes so I have to design 32 masters!
(in the following picture, black masters should be enough)

![g1982](https://user-images.githubusercontent.com/25493297/86511625-2653c600-be10-11ea-84a8-13d5fbb8cc97.png)
![image](https://user-images.githubusercontent.com/25493297/86512198-14c0ed00-be15-11ea-954c-04db06631b62.png)

**Comment by madig** [comment]
Nope. It's not fontmake's job to generate masters for you, you must do that yourself. There are tools to help you do that, MutatorMath was originally written precisely for this: https://vimeo.com/123815114.

**Comment by aminabedi68** [comment]
great :) thank you @madig
