### ISSUE TITLE
Error: copyright & Unknown glyph class

### ISSUE THREAD

**Issue by minjooham** [googlefonts/fontmake#684]
We got two error messages.

1.
INFO:ufo2ft.outlineCompiler:The copyright was normalized for storage in the CFF table and consequently some characters were dropped: 'Copyright 2020 The Hahmlet Project Authors https:github.comhyper-typehahmlet'

2.
fontmake: Error: In 'Hahmlet.glyphs' -> 'master_ufo/Hahmlet.designspace' -> 'master_ufo/Hahmlet-Thin.ufo': Compiling UFO failed: /Users/minjooham/Dropbox/github/hahmlet/sources/master_ufo/Hahmlet-Thin.ufo/features.fea:2894:1: Unknown glyph class @HAN_dashes

The @HAN_dashes is one of the groups for opentype feature GPOS.
@Mark2Mark  @davelab6

**Comment by madig** [comment]
1. The CFF metadata table can only store ASCII I think, so © will be dropped.
2. Is the class in the feature file?

**Comment by minjooham** [comment]
1. we don't have  © in our file. And the "/" is a part of ASCII, why would it drop that?
2. Yes, it is in the feature.fea file. Among other similar named classes. It just complains about this one.

**Comment by punchcutter** [comment]
I've seen this happen with classes when there is a line commented out somewhere in one of the classes. Maybe the class before @HAN_dashes. Deleting the line instead of commenting makes it work.

**Comment by minjooham** [comment]
@punchcutter yes deleting commenting worked. thanks!

**Comment by anthrotype** [comment]
> Deleting the line instead of commenting makes it work.

does that mean the feaLib parser doesn't handle '# comments` inside a class defition? I wonder whether makeotf allows that, or if the FEA spec says anything about it, and whether feaLib should be updated to fix that.
Feel free to open an issue over at fonttools, thanks

**Comment by anthrotype** [comment]
> we don't have © in our file. And the "/" is a part of ASCII, why would it drop that

probably because it has special meaning in postscript language, here you can see the list of characters that ufo2ft filters out:
https://github.com/googlefonts/ufo2ft/blob/e1c08f6efb07a2fb5202d65a90af94dbd599e7e8/Lib/ufo2ft/fontInfoData.py#L259-L283
