### ISSUE TITLE
error GPOS table

### ISSUE THREAD

**Issue by RosaWagner** [googlefonts/fontmake#698]
I have this error I don't know what it means :( 

`fontmake: Error: In 'sources/JetBrainsMono.glyphs' -> 'master_ufo/JetBrainsMono.designspace': Generating fonts from Designspace failed: ((3, [2, 3, 2]), 'int', '.FeatureCount', 'FeatureList', '.FeatureList', 'GPOS', '.table', 'table_G_P_O_S_')`

**Comment by punchcutter** [comment]
It means something in the GPOS features don't match across masters. It's expecting 3, but the two masters only have 2.

**Comment by madig** [comment]
Specifically, one master has GPOS feature more somewhere. Single glyph kerning/positioning? Language diffs?

**Comment by punchcutter** [comment]
I looked at the current sources and one master has a kern pair. I deleted that and everything builds.

**Comment by punchcutter** [comment]
Or if you really want any kern pairs they need to be consistent even if some masters are set to 0. Exporting from Glyphs will do the interpolation even if there isn't a value set on one master (it will just use 0 as the interpolation value at that point), but fontmake doesn't do that.

**Comment by RosaWagner** [comment]
Thank you @punchcutter !
