### ISSUE TITLE
Travis-ci: build is failing on AMD64

### ISSUE THREAD

**Issue by sanjaymsh** [googlefonts/fontmake#700]
Hi,

I am enabling ppc64le build on travis. And while testing, the build is failing on AMD64 itself only with below error:
"ERROR: InterpreterNotFound: python3.6"
Full log can be seen here: https://travis-ci.com/github/sanjaymsh/fontmake/builds/189708095

Please have a look on this.

Thanks !!

**Comment by anthrotype** [comment]
I would rather discuss about ppc64le before I spend time trying to debug why it fails to build..

**Comment by anthrotype** [comment]
I simply never heard of ppc64le. It looks to me too niche to extend official support for. I am happy to review patches to make things compatible with it, but I am not committing any of my time on actively trying to support this, I'm afraid.

**Comment by sanjaymsh** [comment]
ppc64le is a pure little-endian mode that has been introduced with the POWER8 as the prime target for technologies provided by the OpenPOWER Foundation, aiming at enabling porting of the x86 Linux-based software with minimal effort.

**Comment by madig** [comment]
Uh, there seems to be a typo somewhere: https://travis-ci.com/github/sanjaymsh/fontmake/jobs/398816755#L177 -- the env must be written in all-caps, then it should work as expected.

**Comment by sanjaymsh** [comment]
Ohh,  Thanks !!
