### ISSUE TITLE
Support for Devanagari

### ISSUE THREAD

**Issue by tallchai** [googlefonts/fontmake#703]
It seems like `fontmake` does not completely support Devanagari (conjuncts and marks to be specific).

Here's the built font (ttf) through fontmake render "ट्यूब प्रेशर":
<img width="148" alt="Screen Shot 2020-11-01 at 8 24 21 PM" src="https://user-images.githubusercontent.com/73443155/97822024-7ccbf680-1c82-11eb-971f-b9bc5807c829.png">

Here's the built font (ttf) through GlyphsApp export:
<img width="143" alt="Screen Shot 2020-11-01 at 8 33 47 PM" src="https://user-images.githubusercontent.com/73443155/97822038-89e8e580-1c82-11eb-94f2-66f52ef1fe58.png">

The latter is the correct one.
Any pros here for Devanagari? If not, please let me know what can I do to help debug this.
Thanks.

**Comment by punchcutter** [comment]
My guess is that your vowels are somehow not classified as marks in Glyphs. If you select them in Glyphs and go to Edit > Info for Selection they should show as Category Mark and Subcategory Nonspacing. If they don't show that or the checkboxes for Category and Subcategory are not checked then check them, save, and try fontmake again. Also, what are the names for your UU and E vowels? Are they the default Glyphs names? Like uuMatra-deva, eMatra-deva or something else?

**Comment by punchcutter** [comment]
I checked the TTFs in https://github.com/tallchai/chai-type and it seems like the GDEF part is ok, but it doesn't look like the conjuncts have anchors for the marks. It's hard to tell exactly what's going on without the Glyphs source.

**Comment by tallchai** [comment]
Thanks for the replies @punchcutter.
The TTFs that you checked were probably exported through glyphsapp. I've just pushed the TTFs built through fontmake. Could you please take a look again?

Also, the conjuncts in question have the anchors set for the necessary marks (unless, I am missing your point).
Here's the screenshot:
<img width="394" alt="Screen Shot 2020-11-02 at 2 46 34 PM" src="https://user-images.githubusercontent.com/73443155/97912280-9882db80-1d1a-11eb-91f9-df54bd3e318e.png">

**Comment by punchcutter** [comment]
It doesn't look like the conjuncts are getting the anchors. Another thing to check in the Glyphs file is the script setting for those. The way fontmake reads the anchors relies on the script property to group bases (or ligatures) and marks. If all of the conjuncts and the Devanagari marks are set to 'deva' in Edit > Info for Selection then they should get grouped and exported correctly. I see that there are some mixed up groups where 'deva' marks are grouped with the Latin marks and that probably comes from this.

**Comment by tallchai** [comment]
`It doesn't look like the conjuncts are getting the anchors.`
Based on the image in the previous reply, am I not setting them correctly?

I do not have the `script` option checked under Edit > Info for Selection.
<img width="269" alt="Screen Shot 2020-11-02 at 3 36 04 PM" src="https://user-images.githubusercontent.com/73443155/97916599-3679a480-1d21-11eb-9985-05c44d008d36.png">

Should I check the "Script" option (and Category & SubCategory as well)?

**Comment by punchcutter** [comment]
Yes, I think you should check all those and try fontmake again and see if it works. Usually this kind of problem comes from all these settings.

**Comment by tallchai** [comment]
Checked all Script, Category & SubCategory options for all `-deva` glyphs. But, unfortunately, the issue still exists.
I have pushed the source glyphs file to help debugging. 👍

**Comment by punchcutter** [comment]
Ok, something seems wrong with mark to ligature setup. If you change the conjuncts to be Letter/Other instead of Letter/Ligature then it's working for me. There's usually not much reason to classify glyphs as ligatures. If you have ligature carets set up then you need that, but for general conjuncts in most scripts there's usually no need to classify as ligature. Glyphs will automatically call these ligatures because of the names, but for most scripts I just switch that back to Letter/Other.

**Comment by tallchai** [comment]
Thanks a lot @punchcutter That works! 🎉

But is something wrong with my source glyphs file setup for ligatures? I do have the `liga` feature unchecked for updating automatically.

**Comment by punchcutter** [comment]
No, that part is fine. I think this is more about how fontmake is reading the ligature/conjunct anchors and not handling them as expected. If I can find time I'll check into it.

**Comment by tallchai** [comment]
Cool. Good to know.
Thanks again. Closing this thread.
