### ISSUE TITLE
Non-exporting glyphs make their way in the variable font

### ISSUE THREAD

**Issue by kosbarts** [googlefonts/fontmake#708]
Hi, 

In my workflow I design in Glyphs and then use fontmake to generate UFO's and designspace. I need the designspace to manually edit some rules. From there, I fontmake the designspace document and produce a variable font. 

All the Glyphs that are set to non-exporting in Glyphs still make their way in the final variable font, even though the designspace document includes the public.skipExportGlyphs list. 

I have tried the --no-write-skipexportglyphs argument when I fontmake from Glyphs to UFO+designspace. 
I have also tried the  --subset argument when fontmaking from designspace to final VF.

There seems to be no way of forcing fontmake to drop the non-exporting glyphs. 
Am I doing something wrong?
Can this be a bug?

**Comment by madig** [comment]
Without sources, we can't really say.

**Comment by kosbarts** [comment]
I hope this is helpful. It's a demo of the observed issue:

https://github.com/kosbarts/fontmakeVFtest

**Comment by kosbarts** [comment]
@madig any luck with this? Did you get a chance to test it?

**Comment by madig** [comment]
No. I had a quick look but was turned off by the complex build system. I don't have time to debug those. I _may_ be able to help if you make a plain DS file with the lib key plus UFOs, no build system, and it still doesn't work then. Otherwise, you'll have to fix your build script on your own.

**Comment by kosbarts** [comment]
#madig I guess the look was very quick. Before I proceed to _fix my build script on my own_, let's just exclude the possibility fontmake has a bug.

The repo includes the designspace (with lib key info) + UFOs that you want. To save you from having to search here is the link:
https://github.com/kosbarts/fontmakeVFtest/tree/master/production/master_ufo

**Comment by madig** [comment]
> I guess the look was very quick.

Yes, because sorting through a repo to get at the actual bare reproducer data is precisely the kind of mental legwork I don't want to do when I look at a bug report.

In this case, the formatting of the DS file is the culprit. The following two snippets are not parsed the same and you must use the latter:

```
   <key>
    public.skipExportGlyphs
   </key>
   <array>
    <string>
     O.alt
    </string>
    <string>
     Q.alt
    </string>
   </array>
```

```
      <key>public.skipExportGlyphs</key>
      <array>
        <string>O.alt</string>
        <string>Q.alt</string>
      </array>
```

I honestly don't know if they should be parsed as equivalent but this is a corner case IMO.

**Comment by alerque** [comment]
Loose the code prettifier:

https://github.com/kosbarts/fontmakeVFtest/blob/2b5f0b04d5af86288608339a4ec1d0c85c8d460b/production/designspace.py#L1

**Comment by kosbarts** [comment]
@alerque that's awesome. I didn't write the python script but thanks for figuring it out. 

@madig thanks for the effort.
