### ISSUE TITLE
Add support for the Glyphs 3 file format

### ISSUE THREAD

**Issue by RosaWagner** [googlefonts/fontmake#710]
It looks like Fontmake doesn't find the license URL/name ID 14 when exporting from Glyphs 3.

**Comment by davelab6** [comment]
We probably need to define a ufo based production workflow, where users export g3 projects to UFOs + design spaces (made with @simoncozens 's new Pilcrow) and build them with fontmake. I believe the few fontlab 7 based projects like @tphinney 's Science Gothic and @twardoch 's Lato do this already

**Comment by simoncozens** [comment]
Pilcrow is basically going to turn into a GUI for fontmake.

**Comment by RosaWagner** [comment]
For the license thing, Georg has fixed it, it was a bug on their hand, but I have to test it again. For now we can probably use Glyphs (3), as long as we keep "Glyphs 2" as a file format.

**Comment by felipesanches** [comment]
what's the problem with the "Glyphs 3" file format?

**Comment by anthrotype** [comment]
no problem -- just a new different format
(see https://github.com/schriftgestalt/GlyphsSDK/tree/Glyphs3/GlyphsFileFormat/validator).

**Comment by felipesanches** [comment]
is this new file format already supported by fontmake?

**Comment by anthrotype** [comment]
> is this new file format already supported by fontmake?

if it were, we wouldn't be talking here.

**Comment by felipesanches** [comment]
ok, now it is clear. That's the problem. Thanks. ;-)

**Comment by RosaWagner** [comment]
So the question is… is there a plan to support Glyphs3 file format ?

**Comment by anthrotype** [comment]
We'll need to find the time to do it at some point, but I'm afraid I can't give a time frame right now.

**Comment by felipesanches** [comment]
I labeled this issue as "Nice to have" because I believe we will inevitably start getting more and more Glyphs 3 files contributed to the Google Fonts collection. And we would need fontmake to support it so that we can have server-side automated builds of those font files.

**Comment by simoncozens** [comment]
It’s just a matter of having glyphsLib read it, right? Once the structures are loaded, fontmake can consume them just the same as now.

**Comment by felipesanches** [comment]
so, we should move this issue to the glyphsLib tracker ;-)

**Comment by weiweihuanghuang** [comment]
Is the issue I'm having here related? 
https://github.com/weiweihuanghuang/Work-Sans/pull/67
