### ISSUE TITLE
Placement of comb marks with zero width

### ISSUE THREAD

**Issue by philippnurullin** [googlefonts/fontmake#717]
When building with fontmake from Glyphs 2 source *comb* marks like `gravecomb` and others having positive LSB and RSB negative but to work properly it should be the other way around. 

Expected results
<img width="162" alt="Screenshot 2020-12-09 at 17 16 11" src="https://user-images.githubusercontent.com/48058957/101643301-0c648200-3a45-11eb-8384-62377eb26ab8.png">

Actual results
<img width="181" alt="Screenshot 2020-12-09 at 17 16 32" src="https://user-images.githubusercontent.com/48058957/101643308-0e2e4580-3a45-11eb-955a-3cf1a3e3ce42.png">

How this behaviour can be changed?

**Comment by anthrotype** [comment]
maybe related to https://github.com/googlefonts/glyphsLib/issues/547

**Comment by philippnurullin** [comment]
Yes, thanks, it's pretty much related. )
I didn't find the final conclusion. Will this be implemented?

**Comment by anthrotype** [comment]
if you set the advance widths to 0 yourself in the source files (placing the marks wherever you like), glyphsLib will not attempt to set their advance to 0 and they will be where you expect them to be

**Comment by philippnurullin** [comment]
The problem is that i just don’t see why the current export behaviour is useful.

Some programming text editors don’t support OT features. Like terminal apps. Anchors are not working, so the only way to use combined marks is to mimic the placement by having the negative RSB value. 
In general I can’t imagine the case where the positive LSB will be useful (Arabic scripts?). There are some cases where you want to place the mark at the center, but that a rare case and that can be made by hand. 
The second argument is the unity of default behaviour. The world will be a better place if all the USB port were the same. So it will be expected to build from Glyphs source and have same rules of export applied. 

I understood if build scripts won’t do anything with non space marks and the position of “do it by your hands” sounds logical.
But the current export is treating non space marks, and it can treat them better. 

If i will do the placement of all comb marks by hand this will be a lot of very dumb work. And all the work can be easily automated on export. I  mean that’s why we have scripts.

In order to make marks export I will need manually place all the 64x3 marks and this will make them potentially hard to edit in the future. So this is scenario I will want to avoid.

I hope this is somehow change your mind, or maybe there are some aspect i don't see or understand, please share them if it is so.

**Comment by khaledhosny** [comment]
The current behavior is simpler to implement, set the width to 0 and be done with it, so it is the natural choice. It also seems to be the [new behavior of Glyphs 3](https://forum.glyphsapp.com/t/collapse-to-zero-width-glyph-behavior-changed-in-glyphs-3/16520). This is also what will happen if the advance width was not zeroed at build time and left the the OpenType layout engine to zero it, so that is even more consistent.

Proper mark placement require anchors, without anchors you are getting suboptimal results already (unless it is a monospaced font, and even this will still need adjustments for some marks), and with anchors it does not matter when the the glyph is placed relative to its origin.

**Comment by philippnurullin** [comment]
The monospace font it is, in my case. 
Made it by hand, hope there will be no need to edit marks in future. )
Thanks for the reply.
