### ISSUE TITLE
Variable font: mark anchors cause "Base master not found" build error 

### ISSUE THREAD

**Issue by eliheuer** [googlefonts/fontmake#747]
I'm working on a variable font that builds fine with fontmake when marks have no anchors but adding an anchor such as `_top` to one glyph like `dieresiscomb` in all the UFO sources causes the following error:
```
fontmake: Error: In 'sources/Private-Font.designspace': Generating fonts from Designspace failed: ('Base master not found.', 'MarkBasePos', '[0]', 'Lookup', '[1]', 'list', '.Lookup', 'LookupList', '.LookupList', 'GPOS', '.table', 'table_G_P_O_S_')
```
Possibly similar to issue #675

**Comment by eliheuer** [comment]
Interestingly, changing the anchor from `_top` to `top` allows the font to build 🤦.

**Comment by moyogo** [comment]
This seems to be a mismatch in the anchors between masters.

**Comment by eliheuer** [comment]
Thanks! That was it. 🤦

**Comment by vv-monsalve** [comment]
A private project is having a similar Error. Kerning pairs and classes, features and anchors have been inspected but is still having the situation. This is the Error Message

```
fontmake.errors.FontmakeError: In 'YouTubeSans.glyphs' -> 
'master_ufo/Font.designspace': Generating fonts from 
Designspace failed: ((4, [3, 3, 4, 4, 4]), 'int', '.FeatureCount', 
'FeatureList','.FeatureList', 'GPOS', '.table', 'table_G_P_O_S_')
```

**Comment by hyvyys** [comment]
I have this issue right now. I am trying to build a font with a slant axis. I am able to successfully export the font as long as the anchors are in the same position. Once I slant the anchors, the export fails.
