### ISSUE TITLE
Precompiled, standalone binaries for Windows?

### ISSUE THREAD

**Issue by cssobral2013** [googlefonts/fontmake#768]
So, users (especially those from Windows 8.1) don't have the pain to compile, nor have to dual-boot with Linux.

**Comment by cssobral2013** [comment]
This is because, for Example, Windows 8.1 don't have the Subsystem for Linux, so the only way to have Linux, is by dual-booting.

**Comment by anthrotype** [comment]
> the pain to compile

Hm, there shouldn't be any need to actually compile anything from source, when you `pip install fontmake` you should automatically get pre-compiled wheel packages for your python version and platform. If not, we may be missing something.
What python version and architecture (32 vs 64 bit) are you using?
```
$ python --version
Python 3.9.4
$ python -c "import sys, platform; print(platform.architecture()[0]), print(sys.maxsize > 2**32)"
64bit
True
```
