### ISSUE TITLE
Question about using MutatorMath to extrapolate in a simple given example

### ISSUE THREAD

**Issue by aminabedi68** [googlefonts/fontmake#774]
hi
i couldn't use `--use-mutatormath` option to extrapolate an _out of rang_ instance.
so i designed a simple test (3 masters(A-00, A-01, A-10) with 2 axes(weight and contrast) including letter "A"+ "cedilla"+"acute" and "GPOS marks" (I think the hardest part in extrapolating 4th maser(A-11) is the extrapolation of mark anchors))

![text1472](https://user-images.githubusercontent.com/25493297/119250403-16bea680-bbb5-11eb-951a-43ed3ca2e1aa.png)

fontmake doing the job without error([log_ 1.txt](https://github.com/googlefonts/fontmake/files/6526068/log_.1.txt))
and if i use `--interpolate-binary-layout` the same process happens.([log_ 2.txt](https://github.com/googlefonts/fontmake/files/6526069/log_.2.txt))

## Expectation:
(outline extrapolated inside [fontforge](https://github.com/fontforge/fontforge/issues/4584), marks added manually because fontforge can't interpolate/extrapolate ot features)

![fontforge_k74VFn3JTE](https://user-images.githubusercontent.com/25493297/119250837-08be5500-bbb8-11eb-84a0-4d43717d1612.png)

## fontmake output:
A-11 has the same outline of A-10!

![fontforge_64snxXQPCl](https://user-images.githubusercontent.com/25493297/119250874-4327f200-bbb8-11eb-8b78-fd779c7792c0.png)

here are the test files, please take a look:
[A.zip](https://github.com/googlefonts/fontmake/files/6526021/A.zip)
if you have any question to clarify the issue, please ask. thank you.

**Comment by anthrotype** [comment]
You probabaly want to file an issue in MutatorMath repository. We are actually planning to end support for MutatorMath in fontmake, as it's more of an hindrance.

**Comment by aminabedi68** [comment]
thank you @anthrotype
