### ISSUE TITLE
Error when font name in config doesn't match glyphs file

### ISSUE THREAD

**Issue by aaronbell** [googlefonts/fontmake#787]
In converting Museo Moderno to the UFR format, I ran into an issue where the variable font was not generating instances in the `fvar` table. It turned out that the issue was that there was a slight mismatch between the font name in the `config.yaml` file ("Museo Moderno") and the name in the Glyphs file itself ("MuseoModerno"). 

I think that it would make sense to issue an error if there is mismatch between these two locations rather than building the font and silently failing to produce an `fvar` table.

**Comment by anthrotype** [comment]
you mention "config.yaml", so I presume this issue is about https://github.com/googlefonts/gftools/ more than fontmake itself (used by the former)?  /cc @m4rc1e

**Comment by aaronbell** [comment]
Ah yes, that's true. My sense was that fontmake did the heavy lifting in generating the variable font but it might have more to do with builder's calling of fontmake. I'll file a bug over there.

**Comment by anthrotype** [comment]
feel free to reopen if you do find out this has to do with fontmake and not gftools
