### ISSUE TITLE
Fontmake reorders ligatures in problematic ways

### ISSUE THREAD

**Issue by tphinney** [googlefonts/fontmake#793]
I have encountered an issue that may well delay the internal release of a proprietary Google font in development.  😢
I am trying to understand if this is somehow a “feature” in Fontmake and not just a bug? And because my example is for internal Google stuff, I would rather not post it externally on the repo quite yet.
It seems that Fontmake reorders my 'liga' substitutions. Some of this is reasonable: going from largest number of input components to smallest. (But, we were already doing that upstream.) HOWEVER, it does that separately depending on the starting letter of the input; all substitutions starting with "a" are ordered ahead of all substitutions starting with "b".

Let me give a simplified but actual example (albeit with names changed) of why this is a problem. Let’s pretend my font only has four ligatures, each formed from the following strings:
- robin_google_esfahbods
- esfahbod
- google
- robin

In my source, these are ordered longest to shortest as they are above. So "robin_google_esfahbods" would fire and not get missed.

But Fontmake reorders them alphabetically-by-first-letter at compile time, and only after that by length within each first-letter group.

- esfahbod
- google
- robin_google_esfahbods
- robin

So "esfahbod" fires first, breaking up my intended ligature, and I get the three separate ligatures for "robin" "google" and "esfahbod" with some extra underscores between and "s" at the end. (underscored and alphabetic letters are blank in this font, so it just shows extra whitespace).

**Comment by moyogo** [comment]
That's odd. fontTools.otLib.builder.buildLigatureSubstSubtable() uses the number of components, then the alphabetical order.

**Comment by tphinney** [comment]
That would be perfectly sensible! Indeed, that is exactly how we were ordering the 'liga' code upstream.

**Comment by tphinney** [comment]
Or… not really! My bad.

Seems that the ultimate cause of the problem was (1) the correct glyph name itself had a typo, so in spelling it correctly I made the glyph name wrong, combined with (2) an error in our ligature-sorting code that made it look quite different from the correct sort from Fontmake.
Stepping through everything very carefully led me to the correct answers—eventually.
