### ISSUE TITLE
How to avoid calling EraseOpenCornersFilter on Glyphs files?

### ISSUE THREAD

**Issue by jenskutilek** [googlefonts/fontmake#803]
I'm building a variable font from a glyphs file that doesn't use open corners, and the EraseOpenCornersFilter dies with a "division by zero" error on the files. Is there a way to disable running the filter from fontmake cmdline?

**Comment by khaledhosny** [comment]
If you have a sample glyph, we can add another test to the PR.

**Comment by madig** [comment]
I'm looking at this error, I guess it's the same as https://github.com/googlefonts/glyphsLib/issues/703.
