### ISSUE TITLE
Regression: ufo2ft 2.25.0 rejects extra keyword arguments passed by fontmake

### ISSUE THREAD

**Issue by rschiang** [googlefonts/fontmake#817]
Starting from `ufo2ft==2.25.0`, the library will start to reject any unexpected arguments (googlefonts/ufo2ft@c87320c). 

The current version of [`font_project.make_variable_font()`](https://github.com/googlefonts/fontmake/blob/5190dd8/Lib/fontmake/font_project.py#L340), however, passes two of the arguments (`flattenComponents`, `cubicConversionError`) that are only meant to be used with `ufo2ft.compileTTF` but not `ufo2ft.compileVariableTTF`.

We’ll need to either prune the excess arguments or update `ufo2ft` to accept them.

**Comment by anthrotype** [comment]
bumped minimum ufo2ft to 2.25.1 in https://github.com/googlefonts/fontmake/commit/61b064161081fc87752c10f2997d4d58a9e3167b -- which should fix this among other things
