### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by khaledhosny** [googlefonts/fontmake#828]
The last stable release restricts glyphsLub version to 5.x series, should we cut a new stable release to be able to use glyphsLib 6.x? Are there any blockers?

**Comment by anthrotype** [comment]
Yes, we should. I just bumbed all requirements.
I see a few issues that we could easily tackle before release:

https://github.com/googlefonts/fontmake/issues/814
https://github.com/googlefonts/fontmake/issues/785
https://github.com/googlefonts/fontmake/issues/783

maybe these ones too: 
https://github.com/googlefonts/fontmake/issues/759
https://github.com/googlefonts/fontmake/issues/824

**Comment by khaledhosny** [comment]
They are good to have, but they don’t seem to be new issues and I don’t think they should block the release (I’d love working on them, but I currently have few free cycles and need to address more pressing issues).

**Comment by khaledhosny** [comment]
https://github.com/googlefonts/fontmake/releases/tag/v3.0.0
