### ISSUE TITLE
Remove mutatorMath integration

### ISSUE THREAD

**Issue by madig** [googlefonts/fontmake#834]
MutatorMath has been superseded by varLib for general font making (though it may be used as a _design_ tool in other contexts). It reads its input from disk, so supporting it in fontmake has the side-effect that we need to write out intermediate UFOs, which is a waste of time in most cases. Revamping fontmake to produce less waste would need either adapting MutatorMath to read input from memory or just dropping it. Since we have varLib already and are less concerned with the design generation, dropping is the easier option.

**Comment by anthrotype** [comment]
I plan to remove MutatorMath integration soon, so we can finally avoid the need to write out intermediate UFOs.
