### ISSUE TITLE
CompatibilityChecker: improve output

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/fontmake#854]
I'm currently working on RobotoFlex which contains 71 masters. If I delete a single anchor, I get the following output:

<img width="1751" alt="Screenshot 2022-02-11 at 10 48 39" src="https://user-images.githubusercontent.com/7525512/153578574-818035eb-0f01-4ec2-8063-c09d4adcc4e2.png">

If you had 5+ missing anchors, you'd quickly experience fatigue (I'm currently at that phase).

Perhaps it would be nicer to instead have:

```
Fonts had differing anchors in glyph A:
* 70 fonts had "bottom, ogonek, top"
* RobotoFlex opsz8-wght400-wdth100-slnt-1 had "bottom, ogonek"
```

@simoncozens thoughts?

**Comment by simoncozens** [comment]
Yep, I'll tidy it.

**Comment by m4rc1e** [comment]
I don't mind doing this since you're dealing with 100 other things.
