### ISSUE TITLE
featureNames inside non-stylistic-set features raises feaLib error

### ISSUE THREAD

**Issue by tonsky** [googlefonts/fontmake#864]
When trying to build Fira Code https://github.com/tonsky/FiraCode/blob/390c41cc94bb4a33630acef3933bce7e09a9fb34/FiraCode.glyphs

I get this error:

```
[~/ws/FiraCode] fontmake -g FiraCode.glyphs -o ttf --output-path FiraCodeLight.ttf -i "Fira Code Light" 
INFO:fontmake.font_project:Building master UFOs and designspace from Glyphs source
INFO:glyphsLib.classes:Parsing "FiraCode.glyphs" file into <GSFont>
INFO:fontmake.font_project:Interpolating master UFOs from designspace
INFO:fontmake.font_project:Generating instance UFO for "Fira Code Light"
INFO:fontmake.font_project:Building TTF for FiraCode-Light
INFO:ufo2ft:Pre-processing glyphs
INFO:ufo2ft.filters.base:Running EraseOpenCornersFilter on FiraCode-Light
INFO:ufo2ft.filters.base:Running DecomposeComponentsFilter on FiraCode-Light
INFO:ufo2ft.filters.base:Running RemoveOverlapsFilter on FiraCode-Light
INFO:ufo2ft.filters.base:Running CubicToQuadraticFilter on FiraCode-Light
INFO:ufo2ft.filters.cubicToQuadratic:New spline lengths: 1: 345, 2: 2869, 3: 1186, 4: 369, 5: 40, 6: 7
INFO:ufo2ft:Building OpenType tables
fontmake: Error: In 'FiraCode.glyphs' -> 'master_ufo/FiraCode.designspace' -> 'instance_ufo/FiraCode-Light.ufo': Compiling UFO failed: instance_ufo/FiraCode-Light.ufo/features.fea:863:1: Expected glyph class definition or statement: got NAME featureNames
```

The line reported is this:

```
feature zero {
featureNames {
  name "Zero with a dot inside";
};
sub zero by zero.zero;
sub zero.tosf by zero.tosf.zero;
} zero;
```

The same glyphs file is compiled fine with fontmake from August 9, 2021.

I’d appreciate any help! Thanks

**Comment by anthrotype** [comment]
Hi! thanks for the report.
According to the Adobe Feature File spec, `featureNames` blocks are only found within stylistic set features (ss01, ss02, etc.):
https://adobe-type-tools.github.io/afdko/OpenTypeFeatureFileSpecification.html#8.c

how did you add that to your .glyphs file? Does Glyphs.app allow you to add a descriptive name to non-stylistic-set features as well?

**Comment by tonsky** [comment]
Got it! This helps, thanks

**Comment by anthrotype** [comment]
@tonsky i'm curious, did you edit the .glyphs source file in a text editor to add that or you did from within Glyphs.app itself?

**Comment by tonsky** [comment]
I am building it from a script. Some of the features are auto-generated, so I automated this
