### ISSUE TITLE
3.2.0 autohinting logic still not right?

### ISSUE THREAD

**Issue by simoncozens** [googlefonts/fontmake#866]
@marekjez86 reports that in 3.2.0, fontmake is now producing autohinted fonts by default, while 3.1.3 does not. I'm having trouble reproducing, but there it is.

**Comment by marekjez86** [comment]
command that I use
fontmake -g <source>  -i -o otf ttf OR fontmake -m <source> -i -o otf ttf

for any of the following sources

https://github.com/googlefonts/noto-source/tree/main/src/NotoSansGeorgian/*.designspace
https://github.com/googlefonts/noto-source/tree/main/src/NotoSerifGeorgian*.designspace

https://github.com/googlefonts/noto-source/blob/main/src/NotoSansBalinese.glyphs
https://github.com/googlefonts/noto-source/blob/main/src/NotoSansTaiTham.glyphs
https://github.com/googlefonts/noto-source/blob/main/src/NotoSerifOriya.glyphs

Note that it produces autohinted/instance_ttf by default (there's NO instance_otf in autohinted)

**Comment by marekjez86** [comment]
My favorite options would be to produce 1. unhinted only (overriding the source) 2. hinted only (also overriding the source) or 3. BOTH  :-) [because I need both]
