### ISSUE TITLE
Responsibility issue around filters

### ISSUE THREAD

**Issue by yanone** [googlefonts/fontmake#872]
`gftools builder`, on demand, sets two `ufo2ft` filters: `flattenComponents` and `decomposeTransformedComponents` and hands them over in the command at `fontmake.FontProject().run_*()`.

However, when it's a Glyphs source, `glyphsLib` also sets a filter (`EraseOpenCornersFilter`) and links to it in the resulting UFO lib under `com.github.googlei18n.ufo2ft.filters`.

Whenever the filter settings in `gftools` are activated, which is the default, only those are used in `fontmake`, as they are explicitly set, and all implicitly set filters are ignored, such as the one referenced in the UFO.

In my opinion, filters set in the UFO must be used regardless of explicitly set filters, as they are tied to the source.

What’s the policy here? Can the implicitly set filters be included in `fontmake`, or does `gftools` have to read the filters from the lib and set them explicitly?

**Comment by yanone** [comment]
> or does gftools have to read the filters from the lib and set them explicitly?

... which is actually not easy to pull of because at the time of calling `gftools`, no UFO source exists yet to read the value from. It could only set the filter in question explicitly every time, but that won’t fix the repetition of the same situation further in the future when are filters are set implicitly downstream from `gftools`.

**Comment by simoncozens** [comment]
I just hit something similar: adding `--filter DecomposeTransformedComponentsFilter` to the fontmake command line causes filters in the UFO lib to not run.

**Comment by anthrotype** [comment]
so, the fact that command-line --filter(s) override the ones in the source UFOs was by design, it can be useful in some circumstances, but I can see how this is causing confusions.
Maybe we can add a special `--filter='*'` that means "all the ones already listed in the UFO.lib"?

**Comment by anthrotype** [comment]
ufo2ft preProcessor is responsible for activating a series of default filters per-format and loading the user-defined filters from the UFO.lib. It also has `filters` parameter that allows to pass a list of custom filters which makes it skip searching for filters from the UFO.lib (that's the override I was talking about). Fontmake uses that for its --filter command-line option, which I think is what gftools is using (I always discourage people from using the fontmake python API and call it as a console (sub)process for the CLI is supposed to be more stable).

https://github.com/googlefonts/ufo2ft/blob/4f67ab564ed57f499ebfe5f7bf27d7e0b8b47c1e/Lib/ufo2ft/preProcessor.py#L49-L53

So with `--filter='*'` fontmake could load the filters from the UFO.lib (using the same ufo2ft method) and pass them on to ufo2ft compile function.
Alternatively, we add yet another parameter to trickle all the way down that tells ufo2ft to actually extend (and not replace) the list of filters in the UFO.lib

**Comment by anthrotype** [comment]
I believe a similar overriding treatment applies to the --feature-writer option, which replaces the list of writers in the ufo.lib. We could add a `--feature-writer='*'` to the same effect

**Comment by yanone** [comment]
Sounds reasonable
