### ISSUE TITLE
Add support for .ufoz (UFO compressed ZIP format)

### ISSUE THREAD

**Issue by NightFurySL2001** [googlefonts/fontmake#887]
According to [UFO 3 Specification](https://unifiedfontobject.org/versions/ufo3/), a UFO folder may be compressed into a ZIP format file with the extension .ufoz. `fontmake` currently does not support it with the following error: `fontmake: error: Unknown input file extension: xxx.ufoz` 

This will be a very good addition as CJK fonts that need to go up on Google Fonts has tens of thousands of glyphs that uploading the UFO folder is painstakeningly slow (without resorting to using Mac and Glyphs).

**Comment by NightFurySL2001** [comment]
Seems like [`ufoLib2`](https://github.com/fonttools/ufoLib2) can open `.ufoz` files.

**Comment by anthrotype** [comment]
reopening as 

> #900 PR only adds support for reading .ufoz when passed in to the fontmake CLI without the explicit -u flag.
What's left to do for https://github.com/googlefonts/fontmake/issues/887 is also allow ufoz as an additional output format for -o option. That would only be relevant for .glyphs inputs, of course (i.e. if one wants to convert a .glyphs file to a Designspace file + a set of .ufoz masters).

**Comment by NightFurySL2001** [comment]
Actually just noticed there's this line that will need additional support for ufoz too:
https://github.com/googlefonts/fontmake/blob/c6e41deb0cfd679fa2efdf27f472f7c14eea841e/Lib/fontmake/font_project.py#L228
