### ISSUE TITLE
Support for .glyphspackage file format

### ISSUE THREAD

**Issue by arrowtype** [googlefonts/fontmake#923]
I've recently learned about the new-ish `.glyphspackage` file format for GlyphsApp, which saves Glyphs projects in a way that is much better for Git version control. It also apparently is helpful in projects with many glyphs, such as CJK projects (perhaps partly because it helps with Git collaboration?)

In a `.glyphspackage`, each glyph gets its own file, and the package also contains one file for "fontinfo" (metadata, kerning, features, etc), and one file for glyph order. Maybe other files are created where needed.

This makes it much more feasible to collaborate on Glyphs projects via Git, so it would be awesome if FontMake were to support these for builds. As it is, I think I may have to open the package in GlyphsApp, then manually "save as" to convert to a `.glyphs` file for building. This isn't horrible, but isn't as nice as a fully scripted build!

Unfortunately, I am having a hard time finding much documentation on the format on the Glyphs site, and that might be an issue for supporting it here.

The main references are on the forum, like this: https://forum.glyphsapp.com/t/are-glyphspackage-stable/16744

Also related: https://github.com/googlefonts/glyphsLib/issues/801

Maybe @schriftgestalt could give more insight into this?

Thanks!

**Comment by anthrotype** [comment]
sure, once glyphsLib supports parsing those, fontmake should just work (possibly needs to change some assumption about input file extensions)

**Comment by arrowtype** [comment]
That's great news! I wondered whether they might be the case, so thanks for letting me know! I suppose the discussion can mostly take place over there, then.

**Comment by bebraw** [comment]
It looks like glyphsLib supports `.glyphspackage` format now through https://github.com/googlefonts/glyphsLib/pull/803 .

What's missing to complete this issue is changing some assumptions within `fontmake` as mentioned by @anthrotype as currently the cli fails with `'Please supply a file path to a .glyphs file'` when trying to load a `.glyphspackage`.

**Comment by anthrotype** [comment]
I thought that was already addressed in https://github.com/googlefonts/fontmake/pull/931, which was already merged before v3.5.0 release (current is 3.5.1 I think)

**Comment by bebraw** [comment]
> I thought that was already addressed in #931, which was already merged before v3.5.0 release (current is 3.5.1 I think)

Thanks for the heads up! Maybe my version of fontmake is too old. I'll check.

Based on that I would say it's safe to close this issue then.
