### ISSUE TITLE
"No need for avar" in output log by nonliner mapping in variable font build process

### ISSUE THREAD

**Issue by aminabedi68** [googlefonts/fontmake#932]
in one of projects i need this mapping:
```
<mapping input="-1.0" output="-1.0"/>
<mapping input="0.0" output="0.0"/>
<mapping input="0.20408" output="0.0"/>
<mapping input="0.20409" output="0.25"/>
<mapping input="0.408" output="0.25"/>
<mapping input="0.4081" output="0.5"/>
<mapping input="0.6122" output="0.5"/>
<mapping input="0.6123" output="0.75"/>
<mapping input="0.8163" output="0.75"/>
<mapping input="0.8164" output="1.0"/>
```
I write it in designspace axis information and got this in the output log:
```
INFO:fontTools.varLib:No need for avar
```
I tried many things, such as creating avar in a ttx file and putting it in the font with ```ttx -m``` but it was not working. This is the log:
```
Parsing 'avar' table...
WARNING: duplicate entry for 0.2041015625 in axis 'DSTY'
```
I'm pretty sure it used to work earlier. I tried other things like fontmake earlier version, but the result is the same.
I think it's related to **float to hex digit conversion error** somehow.
I still check my typeface sources and build script . I'll report back if I find anything.

**Comment by anthrotype** [comment]
> WARNING: duplicate entry for 0.2041015625 in axis 'DSTY'

that's suspicious, could that be related?

**Comment by anthrotype** [comment]
the element in the designspace XML is called `<map>`, not `<mapping>`, see:

https://fonttools.readthedocs.io/en/latest/designspaceLib/xml.html#map-element

**Comment by aminabedi68** [comment]
> > WARNING: duplicate entry for 0.2041015625 in axis 'DSTY'
> 
> that's suspicious, could that be related?

i used `mapping` for ttx too(which is right), so there is still something wrong maybe.
