### ISSUE TITLE
All strings must be XML compatible: problem with greek

### ISSUE THREAD

**Issue by emmamarichal** [googlefonts/fontmake#938]
Hello!
cc @RosaWagner

When I try to build the font, I got this message: 
```
 raise FontmakeError("Writing UFO source failed", path) from e
fontmake.errors.FontmakeError: In 'master_ufo/Mansalva-Regular.ufo': Writing UFO source failed: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters
```
It disappears when I remove all the greek glyphs... I checked them, I can't find any weird things or problem in the name or somewhere else. I may have looked wrong, but if not, does anyone have any idea what's going on?

Thanks :)

-----

Here is the repo: https://github.com/emmamarichal/mansalva/tree/master/sources

I made a file with my tests without the greek if necessary

**Comment by anthrotype** [comment]
I suspect it might be the presence of control characters, like the error message says, which are invalid in XML. Can you retry with `--verbose DEBUG` option and copy/paste the full error traceback that fontmake spits out?
It's probably coming from fontTools.ufoLib..

**Comment by anthrotype** [comment]
Yeah, looks like there's an [END OF TEXT (0x0003) control character](https://www.fileformat.info/info/unicode/char/0003/index.htm) for some mysterious reasons in yoru sources/Mansalva.glyphs file, at line 78447; no idea how it got there.. It can't be serialized to xml, so you need to strip it.
