### ISSUE TITLE
ttfautohint with fonts as symbol

### ISSUE THREAD

**Issue by typemytype** [googlefonts/fontmake#947]
fontmake ttfautohints fails when a font has no glyph 'o' 

A flag can easily be added while calling ttfautohint from. Now there is no way to provide extra arguments for ttfautohint while using project.run_from_****()

see symbol fonts in the ttfautohint docs:

> Symbol Font
> --symbol, -s
> Process a font that ttfautohint would refuse otherwise because it can’t find a single standard character for any of the supported scripts.
>
> For all scripts that lack proper standard characters, ttfautohint uses a default (hinting) value for the standard stem width instead of deriving it from a script’s set of standard characters (for the latin script, one of them is character ‘o’).
> 
> Use this option – usually in combination with the [--fallback-script](http://freetype.org/ttfautohint/doc/ttfautohint.html#fallback-script) and/or [--fallback-stem-width](http://freetype.org/ttfautohint/doc/ttfautohint.html#fallback-stem-width) option – to hint symbol or dingbat fonts or math glyphs, for example.

**Comment by anthrotype** [comment]
I think you should be able to set the `autohint` parameter, which can be True (use default TTFA options), False (don't autohint), or a string with the arguments to pass to ttfautohint.

Also, we don't really support importing fontmake.FontProjects, only the command line interface is guaranteed to be stable, fontmake isn't designed to be a library. If you can, you should use it as subprocess

**Comment by typemytype** [comment]
> Also, we don't really support importing fontmake.FontProjects

mmm, so generating an unsaved designspace or ufo(s) is not supported from objects? it feels silly to save it first to a temp file on disk to call the same thing over subprocess?

**Comment by anthrotype** [comment]
most of the stuff is done in ufo2ft or fonttools, fontmake being the command line front-end that deals with input/output files (except perhaps for fontmake.instatiator which should really be a separate module or perhaps brought into ufo2ft).
Anyway, you can continue using FontProject.. It's not gonna go tomorrow. Passing `autohint` to the `run_*` methods should work, does it not?

**Comment by anthrotype** [comment]
> autohint off/on is sort of fine, but it will not hint arabic only sources... as this is missing a latin 'o'...

I don't understand what's the problem. The autohint parameter accepts a string with the ttfautohint arguments, have you tried that?
