### ISSUE TITLE
STAT table in features is overwritten by generic STAT table

### ISSUE THREAD

**Issue by kontur** [googlefonts/fontmake#985]
I have a glyphs/ufo+designspace source which includes a STAT table in fea syntax. To my surprise the fonts compiled by fontmake drop the STAT table defined in the sources, and a generic minimal STAT table is added (which also results in those VFs being unusable in e.g. Mac/Word, akin to some of what is discussed [here](https://github.com/google/fonts/issues/3267)). Clearly, a defined STAT table should disable/supersede the automatic generation logic. Also, if the generated STAT table is not actually usable in a meaningful way now that STAT support lands in first apps, it begs the question if it should be emitted at all.

So far I have failed to actually locate _where_ along the fontmake > ufo2ft > fonttools pipe this automatic STAT table is created, in order to disable this behavior or see why it does not respect the existing fea information. **_Any pointers?_**

A [test file](https://www.dropbox.com/s/bbs7bd2p8z5i9ah/STAT.glyphs?dl=0) with explicitly odd axis names for clarity ;) and containing AxisValues:

```
table STAT {
    ElidedFallbackName { 
        name "Standard";
    };
    DesignAxis wght 0 { 
        name "Heaviness";
    };
    DesignAxis wdth 1 { 
        name "Wideness";
    };
    AxisValue {
        location wght 100;
        name "Extralight";
    };
    AxisValue {
        location wght 200;
        name "Thin";
    };
...
```

and running `fontmake -g STAT.glyphs -o variable && ttx -t STAT variable_ttf/Test-VF.ttf` the ttx has the generically constructed STAT table without AxisValue entries:

```
<?xml version="1.0" encoding="UTF-8"?>
<ttFont sfntVersion="\x00\x01\x00\x00" ttLibVersion="4.38">

  <STAT>
    <Version value="0x00010001"/>
    <DesignAxisRecordSize value="8"/>
    <!-- DesignAxisCount=2 -->
    <DesignAxisRecord>
      <Axis index="0">
        <AxisTag value="wght"/>
        <AxisNameID value="270"/>  <!-- Weight -->
        <AxisOrdering value="0"/>
      </Axis>
      <Axis index="1">
        <AxisTag value="wdth"/>
        <AxisNameID value="271"/>  <!-- Width -->
        <AxisOrdering value="1"/>
      </Axis>
    </DesignAxisRecord>
    <!-- AxisValueCount=0 -->
    <ElidedFallbackNameID value="2"/>  <!-- Regular -->
  </STAT>

</ttFont>
```

**Comment by punchcutter** [comment]
That looks totally wrong. This line is forcing to exclude STAT.  https://github.com/fonttools/fonttools/blob/48f68877a8ab5f868f57926b14eb4af1c811dfae/Lib/fontTools/varLib/__init__.py#L998
Then the next line adds the generic STAT unless "STAT" is in the exclude list which in this case would be passed in from https://github.com/googlefonts/fontmake/blob/eef7c40a83cbdbf1317980169fcdc36ebb5c9a12/Lib/fontmake/font_project.py#L420
That doesn't have anything for `excludeVariationTables=('STAT')`. If I add that line and remove "STAT" from the `build_many` line in fontTools then I get the expected STAT from the feature file.

**Comment by kontur** [comment]
The varLib code is hard to read, but I think it does what it should for this use case. The call to `build` will always exclude building a STAT table, but if it isn't explicitly in the `exclude` passed in to `build_many` it will then be built. And assuming it would get that `STAT` as `exclude` it would skip building it, which would be the desired flow here.

But then there is no metric to determine that no STAT table should be built if one is in the features; neither in fontmake or ufo2ft, so it is not excluded and will be automatically built. And there is no way to explicitly tell fontmake not to, unless directly calling that compile method.

As an aside... this kwargs-heavy approach in fontmake makes debugging or understanding anything that goes on in this project very hard indeed. You're somewhere five calls deep and have not the slightest clue what are possible arguments or where they are coming from :/

**Comment by kontur** [comment]
> But then there is no metric to determine that no STAT table should be built if one is in the features; neither in fontmake or ufo2ft, so it is not excluded and will be automatically built. And there is no way to explicitly tell fontmake not to, unless directly calling that compile method.

Or in other words, building the minimal STAT table isn't deliberate, it's just what fontTools happens to do down the line.

**Comment by kontur** [comment]
Seems like escalating this up the chain to ufo2ft or even fonttools is more appropriate for now.

**Comment by anthrotype** [comment]
> no metric to determine that no STAT table should be built if one is in the features

hey sorry I only saw this now. Yes, it appears that we do not properly support building STAT table from features.fea in our VF build pipeline. The STAT support which is in varLib was meant to build a STAT table from a .designspace version 5 which has metadata for that (I wonder if you could use that instead of features.fea? It should be documented in designspaceLib docs and there should be tests for that).

Anyway, IIUC, fonttools varLib.build_many is overwriting a STAT table that feaLib has built early on from the FEA.
I think we should add a check in varLib to prevent that from happening.

from:

`if "STAT" not in exclude:`

to:

`if "STAT" not in vf and "STAT" not in exclude:`

Can you try to see if this works and send a PR?

**Comment by anthrotype** [comment]
I found where the problem is (gonna send a PR myself soon). Basically that line that @punchcutter pointed at, which is forcing to add "STAT" to the list to `exclude` has also the side effect of deleting it altogether from the VF (the latter had inherited a properly built STAT from its base master):
https://github.com/fonttools/fonttools/blob/27758ee1e751a380934a8177153d4130658cbb4c/Lib/fontTools/varLib/__init__.py#L1103-L1105

It's actually not necessary to add "STAT" to exclude when `build_many` calls `build` because `_add_stat` already checks `if "STAT" in font` and returns early if so.

The patch that works for me is the following (i'll send a PR soon):

```diff
diff --git a/Lib/fontTools/varLib/__init__.py b/Lib/fontTools/varLib/__init__.py
index 77b4f4112..8aa15c791 100644
--- a/Lib/fontTools/varLib/__init__.py
+++ b/Lib/fontTools/varLib/__init__.py
@@ -995,11 +995,11 @@ def build_many(
             vf = build(
                 vfDoc,
                 master_finder,
-                exclude=list(exclude) + ["STAT"],
+                exclude=exclude,
                 optimize=optimize,
                 colr_layer_reuse=colr_layer_reuse,
             )[0]
-            if "STAT" not in exclude:
+            if "STAT" not in vf and "STAT" not in exclude:
                 buildVFStatTable(vf, designspace, name)
             res[name] = vf
     return res
```

**Comment by kontur** [comment]
Ah I see... okay, so it actually compiles the STAT from the sources, but it just gets overwritten again. That patch you propose works for my described case 👍
