### ISSUE TITLE
`fsType` output doesn’t honor source UFO metadata for OS/2 table

### ISSUE THREAD

**Issue by ryanbugden** [googlefonts/fontmake#996]
Source UFO files have `fsType` == `0` (No embedding restrictions).

Fonts generated with fontmake output: `<fsType value="00000000 00000100"/>`, regardless of whether ttf or otf.

This is with a simple `fontmake [ufo_path]` command in Terminal.

**Comment by anthrotype** [comment]
strange.. what do you have as openTypeOS2Type in fontinfo.plist?

ufo2ft should set OS/2.fsType to that, only if missing default to [2] => 0x100

**Comment by typemytype** [comment]
the confusing here is the different fallback value for the fsType,  fontMake set this to `[2]` where ufo2fdk takes `[0]` [see](https://github.com/robotools/ufo2fdk/blob/0299fddbd57602fa7b06e1acf05425a553b8deab/Lib/ufo2fdk/outlineOTF.py#L311)

which is wrong in my opinion: the bit 0 doesnt set any restrictions, all other options here are a decisions by someone. Opting for bit 2 feels wrong.

**Comment by khaledhosny** [comment]
At this point, we should be asking for a test UFO file, I suspect the OP is not setting the relevant font info field or giving it the wrong value type causing the fallback to be used.

**Comment by typemytype** [comment]
a UFO has no openTypeOS2Type set in the info plist, so it will return `None`. 

fontmake has a different fallback then ufo2ft and ufo2fdk and the fallback fontmake has makes no sense :)

**Comment by ryanbugden** [comment]
I misspoke. I was under the impression the fsType was set to `0`, but upon double-checking the plist as @anthrotype suggested, it's `None`, sorry for the confusion. 

I think the resulting fsType in the compiled font was unexpected.

**Comment by anthrotype** [comment]
> fontmake has a different fallback then ufo2ft

that's impossible, because fontmake delegates to ufo2ft to create the OS/2 table.

It looks like this is a source issue, so I am going to close. But do reopen if you think otherwise, ideally with a reproducer. Thanks!

**Comment by ryanbugden** [comment]
Curious, where is the choice of `2` coming from here?

https://github.com/googlefonts/ufo2ft/blob/0d2688cd847d003b41104534d16973f72ef26c40/Lib/ufo2ft/fontInfoData.py#L386

**Comment by moyogo** [comment]
@ryanbugden Setting it to 2 when undefined in the UFO is from [ufo2fdk](https://github.com/robotools/ufo2fdk/blob/0299fddbd57602fa7b06e1acf05425a553b8deab/Lib/ufo2fdk/fontInfoData.py#L396) which I’m guessing probably got it from font editing apps back when it was written.

**Comment by typemytype** [comment]
ufo2fdk has 0 as fallback, always have been, bit 2 as fallback makes no sense :) (I keep on repeating)

**Comment by typemytype** [comment]
my mistake: ufo2fdk has this: https://github.com/robotools/ufo2fdk/blob/0299fddbd57602fa7b06e1acf05425a553b8deab/Lib/ufo2fdk/fontInfoData.py#L396 

strange it was never noticed, most of the ufos doesnt set those info values

**Comment by moyogo** [comment]
@typemytype what does that line of code do then?

**Comment by typemytype** [comment]
ufo2fdk has 2 as static fallback and so does ufo2ft... which is maybe up to a change :) to `[0]`

**Comment by moyogo** [comment]
@typemytype @ryanbugden Why should it be [0] "Installable embedding" instead of [2] "Restricted license embedding"? Why not [4] "Preview & Print embedding" or [8] "Editable embedding"?
It sounds like changing the default now would upset everybody who’s been happy with have [2] "Restricted license embedding".
